### ISSUE TITLE
CFLAGS setup assumes gcc compatible flags

### ISSUE THREAD

**Issue by csstup** [dvidelabs/flatcc#10]
In CMakelists.txt, the section that sets up the compiler flags for the final else case assumes you're using GCC.

```
if (CMAKE_C_COMPILER_ID MATCHES "Clang")
(snipped)
elseif (CMAKE_C_COMPILER_ID STREQUAL "GNU")
(snipped)
else()
    # Best effort
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS}" -Wall)
    set(FLATCC_PORTABLE true)
endif()
```

In my case, I'm using the system compiler, not GCC.  I fall into the best effort case.   But -Wall is a GCC flag, not a common compiler option.   Shouldn't the "best effort" case be pretty generic?    I removed -Wall for my testing as it fails otherwise.

**Comment by mikkelfj** [comment]
-Wall is covered by MSVC, ICC, Clang and Gnu at least.

Best effort means what is left after fixing user complaints so I recommend you provide a section for your compiler which I will be happy to include provided it aims for as few warnings as possible, and with consideration for the special portable warnings file that can disable compiler specific hiccups better than in a CMake file. Most special handling in the CMakefile is because certain warnings can't easily be handled in source. In the case of MSVC -W3 was the highest reasonable level, /Wall would break many irrelevant things.

It is intentional that the compiler should fail if not handling -Wall so the CMakefile can be improved based on feedback, otherwise it could easily accept all sorts of strange behaviors that makes the code fragile and difficult to maintain .

**Comment by csstup** [comment]
I guess I read "best effort" as "if not previously defined".   Since you already had GCC and Clang (which support -Wall) I didn't see that having "-Wall" t to the last else case made sense.   You already have the compilers listed that support -Wall.   

But I hear your point about a specific compiler case.   I'll look into what it would take to add that for IBM's XLC.   Thanks!

**Comment by mikkelfj** [comment]
Looking forward to it. The warnings file is here: https://github.com/dvidelabs/flatcc/blob/master/include/flatcc/portable/pwarnings.h

It will only be active if the FLACC_PORTABLE flag is defined, but given that XLC is C11 compliant I doubt it will be needed, unless there is a need to support older versions. The warnings file can be included without the full portable layer if needed.

**Comment by csstup** [comment]
Typo?

include/flatcc/portable/pstdalign.h
```
ifndef PSTDALIGN_H
#define PSTDALIGN_H

#ifndef __alignas_is_defined

#ifndef __cplusplus

/* this whole header only works in C11 or with compiler extensions */
#if !defined (__STD_VERSION) || __STDC_VERSION__ < 201112L

```
Shouldn't this be !defined(__STDC_VERSION__)?    I've never heard of __STD_VERSION.

**Comment by csstup** [comment]
IBM is pretty close to not needing FLACC_PORTABLE.    When compiling the tests, it seems that the only thing it needs it for is to define `alignas`, as it does NOT have `<stdalign.h>`.  Not sure if its coming with a later update to the compiler with C11 or not, but I don't have it.

You already have the C99 extensions coded for in portable/pstdalign.h for _alignas and _alignof.

http://www.ibm.com/support/knowledgecenter/SS4QVT_8.5.1/com.ibm.xlcpp111.aix.doc/language_ref/alignof.html#alignof

However, the tests simply do a 
```
#ifndef alignas
#include <stdalign.h>
#endif
```

Should downstream code for the alignment macros be updated to do an include of portable/pstdalign.h, which woudl define the proper macros (or include stdalign.h if more appropriate) instead?

**Comment by mikkelfj** [comment]
Yes typo, the correct way is to check for __STDC__ first like pinttypes.h does it.
The correct way to do it:
#if (defined(__STDC__) && __STDC__ && defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L)

I cleaned up checks in all portable headers.

**Comment by mikkelfj** [comment]
The general philosophy is that only a few core flatcc headers access portable directly and only files that are generally needed, such as endian support.

I have added pstdalign.h to flatcc_buffers.h and added excemption for GCC versions below 4.7 and __IBMC__ so they do not assume stdaligh.h even if C11 is enabled.

static_assert already has special handling for similar reasons.

Currently several compilers fail in the ci-more branch, and some windows versions fail for other reasons. It will take some time to sort this out.

**Comment by mikkelfj** [comment]
Old GCC now compiles on ci-more, so only Windows left.

**Comment by mikkelfj** [comment]
All supported platforms compile again.

**Comment by csstup** [comment]
Built with latest code.  AIX no longer needs FLATCC_PORTABLE.   yay!

All tests pass.

Here is my suggestion for the root CMakeLists.txt additions to handle IBM XLC.  I added a little debug message to the best effort case too, to help for future compiler porting efforts.

```
<snipped>
elseif (MSVC) # using STREQUAL here conflicts with string interpretation changes in CMake
    # -DFLATCC_PORTABLE also required, but set earlier
    # -W3 is the highest warning level that is reasonable.
    # See include/flatcc/portable/pwarnings.h for disabled warnings.
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -W3 -D_CRT_SECURE_NO_WARNINGS")
    # MSVC 2013 (1800) supports inline variable declations
    # while MSVC 2010 (1600) does not.
    if (MSVC_VERSION STRLESS "1800")
        # Disables monster sample build which uses C99 style variable decls.
        set (FLATCC_NEED_C89_VAR_DECLS true)
    endif()
    set(FLATCC_PORTABLE true)
elseif (CMAKE_C_COMPILER_ID STREQUAL "XL")
    # IBM's native XLC C compiler in extended C99 mode

    message(STATUS "Setting IBM XL C compiler options")
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -qlanglvl=extc99")
else()
    # Best effort
    message(STATUS "Best effort settings for compiler: ${CMAKE_C_COMPILER_ID}")
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wall")
    set(FLATCC_PORTABLE true)
endif()
<snipped>
```

**Comment by mikkelfj** [comment]
great, how about warning levels?

**Comment by csstup** [comment]
By default, XLC has a reasonable level of warnings enabled.   CMake is defaulting to stop on a level of error (with -qhalt=e).    We can enable "deeper" checking of about 20 different things via -qinfo, but in my experience it is a TON of noise.   

See http://www-01.ibm.com/support/docview.wss?uid=swg27046905&aid=7  see -qinfo if you're curious.

IBM provides a cross reference tool to take GCC style CFLAGS and convert them to flags appropriate for XLC.   For -Wall, there is no conversion.   Neither is there one for -pedantic.   That seems to be my experience already.   XL C/C++ is already overly protective without a -Wall like option.

Here's what gets configured by default
-- Configured C_FLAGS:  -qthreaded -qalias=noansi -qhalt=e -qlanglvl=extc99

With these options set, a build is completely clean today, no compiler warnings or errors.

**Comment by csstup** [comment]
If you want, I can do some test builds with some of the options enabled.  Suggestions I would have are:

pro | nopro
Missing function prototypes.
trd | notrd
Possible truncation or loss of data or precision.

For instance, enabling -qinfo=trd gets you things like:
```
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-374 (I) Pointer types "unsigned char*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-374 (I) Pointer types "unsigned char*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-374 (I) Pointer types "unsigned char*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-374 (I) Pointer types "unsigned short*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-374 (I) Pointer types "unsigned short*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-374 (I) Pointer types "unsigned short*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-374 (I) Pointer types "unsigned int*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-374 (I) Pointer types "unsigned int*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-374 (I) Pointer types "unsigned int*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-374 (I) Pointer types "unsigned long long*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-374 (I) Pointer types "unsigned long long*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-374 (I) Pointer types "unsigned long long*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-374 (I) Pointer types "signed char*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-374 (I) Pointer types "signed char*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-374 (I) Pointer types "signed char*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-374 (I) Pointer types "short*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-374 (I) Pointer types "short*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-374 (I) Pointer types "short*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-374 (I) Pointer types "int*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-374 (I) Pointer types "int*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-374 (I) Pointer types "int*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-374 (I) Pointer types "long long*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-374 (I) Pointer types "long long*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-374 (I) Pointer types "long long*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-374 (I) Pointer types "float*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-374 (I) Pointer types "float*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-374 (I) Pointer types "float*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-374 (I) Pointer types "double*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-374 (I) Pointer types "double*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 76.2: 1506-374 (I) Pointer types "double*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 78.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 78.2: 1506-374 (I) Pointer types "unsigned char*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 78.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 78.2: 1506-374 (I) Pointer types "unsigned char*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 78.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 78.2: 1506-374 (I) Pointer types "unsigned char*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 81.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 81.2: 1506-374 (I) Pointer types "unsigned int*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 81.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 81.2: 1506-374 (I) Pointer types "unsigned int*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 81.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 81.2: 1506-374 (I) Pointer types "unsigned int*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 83.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 83.2: 1506-374 (I) Pointer types "int*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 83.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 83.2: 1506-374 (I) Pointer types "int*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 83.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 83.2: 1506-374 (I) Pointer types "int*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 85.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 85.2: 1506-374 (I) Pointer types "unsigned short*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 85.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 85.2: 1506-374 (I) Pointer types "unsigned short*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 85.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 85.2: 1506-374 (I) Pointer types "unsigned short*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 87.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 87.2: 1506-374 (I) Pointer types "unsigned char*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 87.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 87.2: 1506-374 (I) Pointer types "unsigned char*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 87.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 87.2: 1506-374 (I) Pointer types "unsigned char*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 89.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 89.2: 1506-374 (I) Pointer types "unsigned int*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 89.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 89.2: 1506-374 (I) Pointer types "unsigned int*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 89.2: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_endian.h", line 89.2: 1506-374 (I) Pointer types "unsigned int*" and "const void*" are not compatible.
"/work/stupc/flatcc-master/include/flatcc/flatcc_identifier.h", line 58.23: 1506-451 (I) The target integral type cannot hold all possible values of the source integral type.
"/work/stupc/flatcc-master/include/flatcc/flatcc_identifier.h", line 60.23: 1506-451 (I) The target integral type cannot hold all possible values of the source integral type.
"/work/stupc/flatcc-master/include/flatcc/flatcc_identifier.h", line 62.23: 1506-451 (I) The target integral type cannot hold all possible values of the source integral type.
"/work/stupc/flatcc-master/include/flatcc/flatcc_identifier.h", line 64.23: 1506-451 (I) The target integral type cannot hold all possible values of the source integral type.
"/work/stupc/flatcc-master/include/flatcc/flatcc_identifier.h", line 70.18: 1506-495 (I) Pointer type conversion found.
"/work/stupc/flatcc-master/include/flatcc/flatcc_identifier.h", line 70.18: 1506-374 (I) Pointer types "unsigned char*" and "const char*" are not compatible.
<snipped>
```

One of the interesting things is something like this:
```
"/work/stupc/flatcc-master/test/monster_test/monster_test.c", line 729.43: 1506-419 (E) Converting 128 to type "signed char" does not preserve its value.
"/work/stupc/flatcc-master/test/monster_test/monster_test.c", line 731.11: 1506-419 (E) Converting 145 to type "signed char" does not preserve its value.
```

**Comment by mikkelfj** [comment]
OK, since the general level will be caught by clang/gcc the most important part is to avoid a lot of noise for users of the library aiming for a reasonably high warning level of end user code. If you believe this is the default, then fine with me.

**Comment by csstup** [comment]
Most of the -qinfo options are more like lint checking.  VERY strict or to enforce coding styles (like NO GOTO).  

I'm happy to enable any of them and give you the output if you'd like to clean anything up though.

**Comment by mikkelfj** [comment]
the pointer conversion is one of those that may be worth capturing because it is just a single file it seems. I have already removed a lot of similar noise for MSVC, it just needs to be balanced - there are other warnings killed for MSVC. I.e. one can aim for higher levels and disable specific warnings.

**Comment by mikkelfj** [comment]
Then again, I am not really in the mood for tracking all those down. As to the monster test, I'm actually testing those value range boundaries, but could be adapted for less noise.

Lets just go with the default for now and take it up if people complain.
Occasionally these warning hunts track down some pretty nasty bugs, even if it's one in 500.

**Comment by mikkelfj** [comment]
I pushed your proposed settings.

**Comment by mikkelfj** [comment]
Just let me know that it works.

**Comment by csstup** [comment]
Works great!   Thanks!

Note that by default, XLC assumes -O0.   Simple optimizations.

As a test, I did add optimization levels, with PROTOCOL still set to LE.   
With -O0:
`12/13 Test #12: load_test ........................   Passed   51.22 sec`
With -O2:
`12/13 Test #12: load_test ........................   Passed    2.03 sec`
With -O3:
`12/13 Test #12: load_test ........................   Passed    1.91 sec`

Big difference.   

Reference:
```
         -O[<level>]
                Optimizes code at a choice of levels during
                compilation. This is equivalent to
                -qoptimize[=<level>]. <level> can be:

                0
                     Performs only quick local optimizations such
                     as constant folding and elimination of local
                     common subexpressions.
                2
                     Performs optimizations that the compiler
                     developers considered the best combination for
                     compilation speed and runtime performance. The
                     optimizations may change from product release
                     to release.
                3
                     Performs some memory and compile-time
                     intensive optimizations in addition to those
                     executed with -O2. The -O3 specific
                     optimizations have the potential to alter the
                     semantics of a program. The compiler guards
                     against these optimizations at -O2 and the
                     option -qstrict is provided at -O3 to turn off
                     these aggressive optimizations.
                     Specifying -O3 implies -qhot=level=0.
                4
                     This option is the same as -O3, but also:
                       o sets the -qarch and -qtune options to the
                       architecture of the compiling machine.
                       o sets the -qcache option most appropriate
                       to the characteristics of the compiling
                       machine.
                       o sets the -qipa option.
                       o sets the -qhot option to level=1.
                5
                     Equivalent to -O4 -qipa=level=2.

                Specifying -O with no <level> is equivalent to
                specifying -O2.

                Default: -O0

```

**Comment by mikkelfj** [comment]
Optimizations are really important for flatcc - it makes tons of assumptions of small function inlining.

You may also want to run the scritps/benchmark.sh

The load test runs at 0.82 seconds debug build and 0.77 seconds release on my macbook pro iCore 7 2.2Ghz. Strangely, the load test is a bit faster for big endian buffers, but that is not the general picture. I mentioned in in the readme: https://github.com/dvidelabs/flatcc#endianness

I tried to find some compiler byteswap intrinsics for IBM, but IBM has a long document about endian ports without mentioning anything. There are some very secret assembly hacks that I'm not going to dive into. It seems logical operations are generally required on RISC.

BTW: I just pushed size prefixed buffers. It currently breaks 32-bit Windows builds. When it works I'd like a retest, and then 0.4.0 should be good to go.

**Comment by mikkelfj** [comment]
The scripts/test.sh runs to CMake configurations, build/Debug and build/Release using:

cmake ../.. -GNinja -DCMAKE_BUILD_TYPE=Debug
cmake ../.. -GNinja -DCMAKE_BUILD_TYPE=Release

**Comment by csstup** [comment]
Optimization: 
Should we add -O2 to the CMakeFiles.txt/CFLAGS list for XLC?   Probably.

Intrinsics:
Yeah there aren't any.   Your byte operations are fine as they are, and with optimization are pretty damn fast anyway.

Benchmark:
Testing the benchmark, so far a couple failures.
Looks like it doesn't use CMake, so all the options set are not carried forward.   This means a different compiler for me (`cc `defaults to C89).    Since the code has C99 style comments in it, it bombs out immediately.    There are also compile options that aren't valid (-std=c11, etc) in thjere.

I run `CC=xlc benchraw/run.sh`, and I get:
```
running flatbench for raw C structs (debug)
----
operation: flatbench for raw C structs encode (debug)
elapsed time: 0.287 (s)
iterations: 1000000
size: 288 (bytes)
bandwidth: 1005.193 (MB/s)
throughput in ops per sec: 3490255.207
throughput in 1M ops per sec: 3.490
time per op: 286.512 (ns)

operation: flatbench for raw C structs decode/traverse (debug)
elapsed time: 0.717 (s)
iterations: 1000000
size: 288 (bytes)
bandwidth: 401.638 (MB/s)
throughput in ops per sec: 1394577.603
throughput in 1M ops per sec: 1.395
time per op: 717.063 (ns)
----
running flatbench for raw C structs (optimized)
----
operation: flatbench for raw C structs encode (optimized)
elapsed time: 0.107 (s)
iterations: 1000000
size: 288 (bytes)
bandwidth: 2688.122 (MB/s)
throughput in ops per sec: 9333756.464
throughput in 1M ops per sec: 9.334
time per op: 107.138 (ns)

operation: flatbench for raw C structs decode/traverse (optimized)
elapsed time: 0.319 (s)
iterations: 1000000
size: 288 (bytes)
bandwidth: 903.116 (MB/s)
throughput in ops per sec: 3135818.574
throughput in 1M ops per sec: 3.136
time per op: 318.896 (ns)
----
```
The others are hit and miss due to compiler options and such.

**Comment by mikkelfj** [comment]
The benchmark isn't really fully portable as is, but you should be able to hack it if you care.
Just edit the single file in bench_flatcc/run.sh

I recently added the meson branch which is experimental support of a new build system where the benchmark is supported, but it hasn't been merged with latest. I take it you won't bother with that, otherwise let me know.

I don't think we should add -O2 to the options. CMake should do this automatically with Release version as mentioned above. Users can also add their own variants or integrate the runtime files directly in their respective projects.

The benchmark output you copied is from a reference benchmark ported from Google - it doesn't run flatcc code. You can target specific benchmarks more directly.

**Comment by mikkelfj** [comment]
Can I get you to retest?

There is now support of size prefixed buffers which potentially might break things since buffer alignment differ. It broke lots of Windows and old gcc, but is now fully operational.

pstdalign.h and a new paligned_alloc.h have been added and the compiler checks have been updated.

I'm not sure if the IBM checks that set ..._MISSING flags are needed since IBM ought not define C11.
So if you comment those out and see if it works, the files could perhaps get cleaner up.

These are the last changes planned for 0.4.0, so essentially just needs at confirmation test and perhaps a cleanup.

**Comment by csstup** [comment]
Sure.  I'll test shortly.   

XLC has multiple entry points, and we're using the C (99) compiler option.  So no C++ options are enabled, and it won't be reporting ANY C++11 features at all.

**Comment by mikkelfj** [comment]
The concern is also if someone else uses C11 if available, but there is only so much we can test. With the current settings C11 is fully disabled. If the checks are removed, the library may or may not work with C11 - which is probably better if possible - then it can be fixed rather than keep using old fallbacks.

**Comment by csstup** [comment]
Downloaded latest master.  Build with PROTOCOL LE.   All tests pass.

Q:
Would you like me to test with reflection turned back on?  Or is that still a non-starter?

Suggestion (I know not part of this issue)
How about outputting the schema into the generated header files?    I was looking at the monster test stuff and the generated headers for field access.   It would be helpful to know what schema they were built under.   It could just be added as comments verbatim?

**Comment by mikkelfj** [comment]
Reflection should work by now.
BE test would also be nice.

Good point about schema, but since the file names are derived directly from the schema basename you already have the information. The the full parth shouldn't be there anyway. Included files are designed to be the same regardless of how they work included, or generated directly, so it makes no sense to place information there either.

**Comment by mikkelfj** [comment]
There are currently no automated tests for BE encoded buffers on either endian host platform, but I consider the 0.4.0 a well testet reference point - so if anything breaks this is the goto version.

**Comment by mikkelfj** [comment]
I just pushed a "be" branch - this will run some tests on windows, linux and macos for recent compilers.

**Comment by csstup** [comment]
Reflection on, protocol LE: all tests pass
Reflection on, protocol BE: all tests pass

**Comment by mikkelfj** [comment]
Smooth :) then we just need the IBM flag test.

**Comment by csstup** [comment]
Which files am i looking at?  include/flatcc/portable/pstdalign.h?

**Comment by mikkelfj** [comment]
that and paligned_alloc.h

**Comment by csstup** [comment]
xlc (which is in C99 mode) returns:
#define __STDC_VERSION__ 199901L

So I would say that 
#if defined(__IBMC__)
#undef PORTABLE_C11_STDALIGN_MISSING
#define PORTABLE_C11_STDALIGN_MISSING
#endif

**isn't needed**, as it will fall into the case of NOT having the C++11 stdalign include.

**Comment by csstup** [comment]
Maybe indicate what filename the schema was in?   

/* Generated from monsters.fbs by flatcc 0.3.6-dev FlatBuffers schema compiler for C by dvide.com */

I'm thinking of my coworkers down the line.   The generated headers are a bit hard to grok.   Having a copy of the schema in there would go a long way to seeing what goes with what.

**Comment by mikkelfj** [comment]
I will consider adding such a comment, but not right now. A define listing the generators version could also be useful.

Could you please verify that it is ok without the flags - my experience tells me that it is impossible to make sane reasoning about flag behavior ... but I agree with you logic, that is why I am asking you to verify.

**Comment by mikkelfj** [comment]
The very first prototype of the code generator actually copied the schema in comment.

**Comment by mikkelfj** [comment]
Please also note that C11 is not the same as C++11 although there are overlaps.

**Comment by csstup** [comment]
C11:  Right, I knew that.  Just wasn't thinking straight.  :)  

I'm using XL C 12.1, which says it supports "some" C11 features.   By default we're using `extc99 `mode, which C99 in STDC_VERSION.   If we wanted C11 features we'd need to use the `extc1x `mode.
https://www.ibm.com/developerworks/rational/library/support-iso-c11/

XL C version 13 is current, but because my development is still on AIX5.3, I can't upgrade to that yet (requires AIX6.1 or later).  

Removing the flags from both pstdalign.h and palligned_alloc.h still gets a clean compile and tests on both LE and BE.   Its falling into the "Im not anything later than C99" logic.

**Comment by mikkelfj** [comment]
Thanks, yes i suspected that limitation in the environment.

I was about to say that we should then remove the flag, but then I read through the documentation and searched for alignof and aligned_alloc. It seems XLC is not yet ready and we should leave the flags as is. clang and gcc also needs some level support.

But it still important to know that C99 does not rely on these flags.

Let me know your opinion on this.

**Comment by csstup** [comment]
With pstdalign.h:

IBM supports alignof and the aligned attribute as an extension to C99 by default.   Its detected with 
`#define __IBM_ALIGNOF__ 1`


http://www.ibm.com/support/knowledgecenter/SSGH2K_13.1.2/com.ibm.xlc131.aix.doc/language_ref/alignof.html
http://www.ibm.com/support/knowledgecenter/SSGH2K_13.1.2/com.ibm.xlc131.aix.doc/language_ref/var_attrib_aligned.html

So i would say make a special case for `__IBM_ALIGNOF__`   I think its just as simple as:

```
#if ((defined(__STDC__) && __STDC__ && defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L) && \
    !defined(PORTABLE_C11_STDALIGN_MISSING))
/* C11 or newer */
#include <stdalign.h>
#else

#if defined(__GNUC__) || defined (__IBM_ALIGNOF__) || defined(__clang__)
#define _Alignas(t) __attribute__((__aligned__(t)))
#define _Alignof(t) __alignof__(t)
#elif defined(_MSC_VER)
#define _Alignas(t) __declspec (align(t))
#define _Alignof(t) __alignof(t)

#else
#error please update pstdalign.h with support for current compiler
#endif

```

**Comment by mikkelfj** [comment]
Updated with new flag, but keep the IBM _MISSING thing since there is no documentation about C11 support yet, so it would just break unnecessariy (reverting on my previous stance ...)

**Comment by mikkelfj** [comment]
Made the 0.4.0 release - thanks again for helping out with this - getting BE support was a major feature to complete.
