### ISSUE TITLE
x86_64 shared object deploy

### ISSUE THREAD

**Issue by nebiun** [dvidelabs/flatcc#103]
Hi, 
to deploy 64 bit libraries (shared objects) I modified a little some CMake .txt files and added a new flag to create a new lib64 directory.
Running CMake with -DFLATCC_X64=on do the work.
Example (bash script that installs all in a trash directory):

```
#!/bin/bash
 
SOURCEDIR=/root/flatcc-0.5.2
cd ${SOURCEDIR}/scripts/
./initbuild.sh
cd ../build
mkdir install
cd install
cmake ../.. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug -DFLATCC_RTONLY=off -DFLATCC_INSTALL=on -DFLATCC_TEST=off -DBUILD_SHARED_LIBS=on -DFLATCC_X64=on
make
make install DESTDIR=/tmp/target
```

These are the changes:

```
**diff CMakeLists.txt ../original/flatcc-0.5.2/CMakeLists.txt**
95,97d94
< # Architecture
< option (FLATCC_X64 "Compile for 64bit" OFF)
<
243,249c240
< set(lib_dir lib)
< if (FLATCC_X64)
<     set(lib_dir lib64)
< endif()
< message(STATUS "library ${lib_dir}")
<
< set(LIBRARY_OUTPUT_PATH ${PROJECT_SOURCE_DIR}/${lib_dir})
---
> set(LIBRARY_OUTPUT_PATH ${PROJECT_SOURCE_DIR}/lib)
290,291c281,282
<     ARCHIVE_OUTPUT_DIRECTORY "${dist_dir}/${lib_dir}"
<     LIBRARY_OUTPUT_DIRECTORY "${dist_dir}/${lib_dir}"
---
>     ARCHIVE_OUTPUT_DIRECTORY "${dist_dir}/lib"
>     LIBRARY_OUTPUT_DIRECTORY "${dist_dir}/lib"
```

```
**diff src/compiler/CMakeLists.txt ../original/flatcc-0.5.2/src/compiler/CMakeLists.txt**
41c41
<     install(TARGETS flatcc DESTINATION ${lib_dir})
---
>     install(TARGETS flatcc DESTINATION lib)`

`**diff src/runtime/CMakeLists.txt ../original/flatcc-0.5.2/src/runtime/CMakeLists.txt**
15c15
<     install(TARGETS flatccrt DESTINATION ${lib_dir})
---
>     install(TARGETS flatccrt DESTINATION lib)

```

**Comment by mikkelfj** [comment]
I don't think this is the right way to do it.
Setting FLATCC_X64 would imply that the build should be 64-bit, but that is not necessarily true, depending on the build platform.

Instead it is better to specify a custom lib install directory. I'm not sure if this works out of the box

cmake .. -DLIB_INSTALL_DIR=lib64

otherwise something like

https://github.com/htacg/tidy-html5/pull/300

might be a way to accomplish this.

**Comment by mikkelfj** [comment]
See also https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html

**Comment by nebiun** [comment]
None of suggested solutions work for me.
New solution: using 'uname -m' to select correct installing directory for libraries.

 diff CMakeLists.txt ../original/flatcc-0.5.2/CMakeLists.txt
143,149d142
< execute_process(COMMAND uname -m OUTPUT_VARIABLE machine)
< if (machine MATCHES "x86_64")
<     set(lib_dir lib64)
< else()
<     set(lib_dir lib)
< endif()
< message(STATUS "library ${lib_dir}")
247c240
< set(LIBRARY_OUTPUT_PATH ${PROJECT_SOURCE_DIR}/${lib_dir})
---
> set(LIBRARY_OUTPUT_PATH ${PROJECT_SOURCE_DIR}/lib)
288,289c281,282
<     ARCHIVE_OUTPUT_DIRECTORY "${dist_dir}/${lib_dir}"
<     LIBRARY_OUTPUT_DIRECTORY "${dist_dir}/${lib_dir}"
---
>     ARCHIVE_OUTPUT_DIRECTORY "${dist_dir}/lib"
>     LIBRARY_OUTPUT_DIRECTORY "${dist_dir}/lib"

 diff src/compiler/CMakeLists.txt ../original/flatcc-0.5.2/src/compiler/CMakeLists.txt
41c41
<     install(TARGETS flatcc DESTINATION ${lib_dir})
---
>     install(TARGETS flatcc DESTINATION lib)

 diff src/runtime/CMakeLists.txt ../original/flatcc-0.5.2/src/runtime/CMakeLists.txt
15c15
<     install(TARGETS flatccrt DESTINATION ${lib_dir})
---
>     install(TARGETS flatccrt DESTINATION lib)


mikkelfj what do you think about this? Can it be adopted for the distribution?

**Comment by mikkelfj** [comment]
I'm sorry, but this is entirely not possible:

> execute_process(COMMAND uname -m OUTPUT_VARIABLE machine)

This assumes that the system includes a "uname" command, which is unlikely on Windows. It also assumes that you are always building on the same system as the target, which is likely, but not always the case.

Could my above suggestions work if you created you own build.sh to produce the install library give that as an argument, either to an existing CMAKE option like DLIB_INSTALL_DIR, or a custom, optional, option.

BTW:
You may also want to have a look at the meson branch which uses a different build system (Meson):
https://github.com/dvidelabs/flatcc/tree/meson

**Comment by nebiun** [comment]
And this?
Work well where we have uname (and if we want compile for 32 bit on a 64 bit machine)

```
diff CMakeLists.txt ../original/flatcc-0.5.2/CMakeLists.txt
143,158d142
< find_program(<UNAME> uname)
< if (UNAME-NOTFOUND)
<     set(lib_dir lib)
< else()
<     execute_process(COMMAND uname -m OUTPUT_VARIABLE machine)
<     if (machine MATCHES "x86_64")
<         if (CMAKE_C_FLAGS MATCHES ".*-m32[ ]*.*")
<             set(lib_dir lib)
<         else()
<             set(lib_dir lib64)
<         endif()
<     else()
<         set(lib_dir lib)
<     endif()
< endif()
< message(STATUS "library ${lib_dir}")
256c240
< set(LIBRARY_OUTPUT_PATH ${PROJECT_SOURCE_DIR}/${lib_dir})
---
> set(LIBRARY_OUTPUT_PATH ${PROJECT_SOURCE_DIR}/lib)
297,298c281,282
<     ARCHIVE_OUTPUT_DIRECTORY "${dist_dir}/${lib_dir}"
<     LIBRARY_OUTPUT_DIRECTORY "${dist_dir}/${lib_dir}"
---
>     ARCHIVE_OUTPUT_DIRECTORY "${dist_dir}/lib"
>     LIBRARY_OUTPUT_DIRECTORY "${dist_dir}/lib"

```

**Comment by mikkelfj** [comment]
It's better, but it will still break existing packets that rely on current behaviour and it will depend on the host system, not the target system.
I think detection should be based on the compiler flags, not the system runtime.
But I don't know enough about this, and I hesitate to make changes to default behaviour here.

I'd really prefer to keep detection outside of the main CMake file for now and leave it to a user script for now.

There doesn't seem to be standard way to do this:
https://stackoverflow.com/questions/11944060/how-to-detect-target-architecture-using-cmake

I think it would be a lot easier to achieve with the Meson build, but even then, I'd hesitate changing the default libdir configuration.

**Comment by mikkelfj** [comment]
If you can provide a shell script for a specific build you have in mind, perhaps I could add it to the scripts folder as an alternative to build.sh.

**Comment by mikkelfj** [comment]
For example, I think your latest suggested solution would break on MacOS.

**Comment by nebiun** [comment]
Main problem is the hardcoded name "lib" in CMake scripts.
Adding a -DFLATCC_INSTALL_LIB=lib64 with default lib?

Like this:
```
diff CMakeLists.txt ../original/flatcc-0.5.2/CMakeLists.txt
143,148d142
< if (NOT DEFINED FLATCC_INSTALL_LIB)
<     set(lib_dir lib)
< else()
<     set(lib_dir ${FLATCC_INSTALL_LIB})
< endif()
< message(STATUS "library install dir ${lib_dir}")
246c240
< set(LIBRARY_OUTPUT_PATH ${PROJECT_SOURCE_DIR}/${lib_dir})
---
> set(LIBRARY_OUTPUT_PATH ${PROJECT_SOURCE_DIR}/lib)
287,288c281,282
<     ARCHIVE_OUTPUT_DIRECTORY "${dist_dir}/${lib_dir}"
<     LIBRARY_OUTPUT_DIRECTORY "${dist_dir}/${lib_dir}"
---
>     ARCHIVE_OUTPUT_DIRECTORY "${dist_dir}/lib"
>     LIBRARY_OUTPUT_DIRECTORY "${dist_dir}/lib"

```
And run cmake with:
cmake ../.. -DCMAKE_INSTALL_LIBDIR=lib64 -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug -DFLATCC_RTONLY=off -DFLATCC_INSTALL=on -DFLATCC_TEST=off -DBUILD_SHARED_LIBS=on **-DFLATCC_INSTALL_LIB=lib64**

**Comment by mikkelfj** [comment]
That is a lot better, but I don't understand the CMake install command well enough.

What you are actually doing is changing the name of `<projectdir>/lib` locally, which is perhaps ok.

And as for CMAKE_INSTALL_LIBDIR, on my machine, I get the warning:
```
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_INSTALL_LIBDIR
```
also when upgrading the CMakeList.txt script to use CMake 3.0.2, or 3.6.0 (which I can't due to ancient build servers).

The message about install dir also isn't precise because again, it refers to the local dir name.

So in brief, I think you are getting closer, but I need to better understand what is going on.

**Comment by mikkelfj** [comment]
Maybe the problem is really that the CMakeList.txt file uses a simplistic install method, just copying <project>/lib into the system, and it would work correctly if a better method were used?

If that is true, it would be better to solve that, because then hopefully CMake can figure out to add lib64 when needed.

**Comment by mikkelfj** [comment]
@derosier do you have any input on this?

**Comment by nebiun** [comment]
Sorry, this
-DCMAKE_INSTALL_LIBDIR=lib64
is not needed (rest of an(other) old try....)

**Comment by mikkelfj** [comment]
But still, how about looking into the actual install method used?

**Comment by mikkelfj** [comment]
I'll consider adopting your last proposal, but I'll leave this issue open for a while in case you or others come up with a better install method.

**Comment by nebiun** [comment]
Ok.
Thankyou!

**Comment by mikkelfj** [comment]
Added FLATCC_INSTALL_LIB option as suggested.
