### ISSUE TITLE
flatcc/flatcc_prologue.h: No such file or directory  #include "flatcc/flatcc_prologue.h"

### ISSUE THREAD

**Issue by FerenczD** [dvidelabs/flatcc#106]
This might be a silly question, but I'm trying to build my own C (with gcc) project using flatcc, and this error appears
       flatcc/flatcc_prologue.h: No such file or directory
       #include "flatcc/flatcc_prologue.h"

I created and compiled my schema, and it happens when I run my gcc command 

I think I know why happens I just don't know how to solve it

The flatcc installation is in a totally different directory as my project, and I'm assuming to solve this issue would be to make the includes/libraries as global. Is that right? If so, how do you do that?

I'm still getting used to Linux

Thanks

**Comment by mikkelfj** [comment]
Could you please test the new Introduction section I added a few minutes ago (before seeing your question) I will create a seperate test project directory with links to the flatcc includes and binaries without a global installation.

I guess you are just not having the `-I include path` set correctly, and the above produces a shell build script with all that set up.

**Comment by mikkelfj** [comment]
https://github.com/dvidelabs/flatcc#introduction

**Comment by FerenczD** [comment]
I followed the introduction and when building the project was giving me the same project. This is my gcc call gcc monster.c -o monster ../../flatcc/lib/libflatcc.a

**Comment by mikkelfj** [comment]
yes, you are missing `-I include` for libraries.

(And possibly also the path to the headers generated with flatcc, but given the error you get, they are already in your path).

If you run the generated build script `scripts/build.sh` that should happen automatically.
here is part of the debug build in the script

    CFLAGS="$CFLAGS -I ${ROOT}/include -I ${ROOT}/generated"
    CFLAGS_DEBUG=${CFLAGS_DEBUG:--g}
    $CC $CFLAGS $CFLAGS_DEBUG ${ROOT}/src/*.c ${ROOT}/lib/libflatccrt_d.a -o ${NAME}_d

This roughly expands to

    cc -I ./include -I ./generated -g ./src/monster.c ./lib/libflatccrt_d.a -o monster_d

where cc is the system C compiler, often gcc or clang.

**Comment by mikkelfj** [comment]
And release build would be

    cc -I ./include -I ./generated -O2 -DNDEBUG ./src/monster.c ./lib/libflatccrt.a -o monster

**Comment by mikkelfj** [comment]
Since you say that you are new to Linux, the -g option is for adding debug symbols. You can use gdb to debug the program. Often if you do something wrong, an assertion is raised in debug, and then can get more information that way.

**Comment by mikkelfj** [comment]
With your project, it would likely be

    gcc monster.c -o monster -I../../flatcc/include ../../flatcc/lib/libflatcc.a

**Comment by FerenczD** [comment]
The scripts/build.sh quite didn't work for me. However, it worked after adding the -I ../../flatcc/include as you mentioned. 
I didn't know about the GDB  debug, I will take a look at that. Thanks for the help

**Comment by mikkelfj** [comment]
OK, I'm glad it worked out. If you later on figure out why the script didn't work for you, please let me know so I can improve the setup script, or documentation.
