### ISSUE TITLE
IBM's XLC needs math library linked in 

### ISSUE THREAD

**Issue by csstup** [dvidelabs/flatcc#11]
`json_parser.c` uses the` isinf() `function, which requires the math library to be linked in to any executable bound to the lib.a objects.

I don't know enough about Cmake to know where to add LDFLAG type options so that final targets that use the lib.a libraries get `-lm` added.    Could you point me in the right direction?

**Comment by mikkelfj** [comment]
I quick answer that needs more research. The isinf() should not require a special math library dependency assuming the usual floating point format. It can easily be implemented as a two line C macro - I just don't recall the details. It is specific to the grisu algorithm which you can also test separately in https://github.com/dvidelabs/flatcc/tree/master/external/grisu3

**Comment by csstup** [comment]
I dunno if I would consider -lm a "special" math library.  Its pretty common on AIX that I have to include it for any #include <math.h> functions.   GNU C Lib has all that stuff included in libc, so no additional library link is required.

**Comment by mikkelfj** [comment]
Yes, but it is still unwanted complexity, which is exemplified by this issue. Keep in mind that you don't need CMake and all that. For the runtime flatcc support you just need a subset of the src/runtime/*.c files, so you don't want to mess with linker settings in an existing project.

**Comment by csstup** [comment]
I can't build the tests without it.

(snipped output of scripts/build.sh)
```

Scanning dependencies of target test_json
[ 84%] Building C object test/json_test/CMakeFiles/test_json.dir/test_json.c.o
Linking C executable test_json
ld: 0711-317 ERROR: Undefined symbol: ._isinff
ld: 0711-345 Use the -bloadmap or -bnoquiet option to obtain more information.
test/json_test/CMakeFiles/test_json.dir/build.make:89: recipe for target 'test/json_test/test_json' failed
gmake[2]: *** [test/json_test/test_json] Error 8
CMakeFiles/Makefile2:1736: recipe for target 'test/json_test/CMakeFiles/test_json.dir/all' failed
gmake[1]: *** [test/json_test/CMakeFiles/test_json.dir/all] Error 2

```

isinff() is what IBM maps isinf() to if the argument is sizeof(float) via macro.   Its in -lm.

**Comment by mikkelfj** [comment]
I was mistaken when I said it happened in grisu3 - grisu3 does its own inf handling but the portable parser must follow the strtod standard of returning isinf which the json parser depends upon.

I added cleaner functions for checking parse range errors and a fallback implemention for isinf and an option to use isinf for unrecognized compilers when HAVE_ISINF is defined. This way you can either link with libmath in you projects (outside of CMake setup), or use the fallback when running tests etc.

Please let me know if it works - on clang both options work. Affected files:
include/flatcc/portable/pparsefp.h
src/runtime/json_parse.c

**Comment by mikkelfj** [comment]
Updated the api so PORTABLE_USE_ISINF is used instead of HAVE_ISINF which breaks the portable library conventions. It forces the use of isinf if not known to be supported directly (gcc, clang, msvc). On XLC this can be used to favor isinf when -lm is linked in without forcing the dependency. Added +1,0,-1 semantics for parse_double/float_is_range_error(value) and updated comments to discourage use of isinf directly in relation to float parsing.

**Comment by csstup** [comment]
Tests are building now, but due to another issue (just posted) I can't verify the tests themselves yet.
