### ISSUE TITLE
All testcases crash when use -DFLATCC_USE_GENERIC_ALIGNED_ALLOC 

### ISSUE THREAD

**Issue by charleszhangjie** [dvidelabs/flatcc#118]
I wonder there exists some errors in include/flatcc/flatcc_alloc.h at line 107:
https://github.com/dvidelabs/flatcc/blob/8f88bf257d3d652b53b89e5298bda9badb833ab0/include/flatcc/flatcc_alloc.h#L99-L109

I think it should define `FLATCC_ALIGNED_FREE` rather than `FLATCC_ALIGNED`, it will effect when FLATCC_USE_GENERIC_ALIGNED_ALLOC  defined.
I try this:
- set macro `-DFLATCC_USE_GENERIC_ALIGNED_ALLOC ` in CMakeLists.txt
- run `scripts/initbuild.sh make` 
- run `scripts/test.sh`

all test cases crash because of invalid pointer when do free.

Moreover, I find some errors in test code of test/json_test/test_json.c:114
https://github.com/dvidelabs/flatcc/blob/8f88bf257d3d652b53b89e5298bda9badb833ab0/test/json_test/test_json.c#L113-L126

when `flatbuffer` is not used and assigned above, it is zero when call flatcc_builder_aligned_free, it will lead to segment fault in function `__flatcc_aligned_free`
In addition,  the test case 3 monster_test always fails but I can not find the reason.

**Comment by mikkelfj** [comment]
I certainly looks like a mistake.

Does all these problems go away if FLATCC_ALIGNED is changed to FLATCC_ALIGNED_FREE as you suggest, or are there more issues?

**Comment by charleszhangjie** [comment]
> I certainly looks like a mistake.
> 
> Does all these problems go away if FLATCC_ALIGNED is changed to FLATCC_ALIGNED_FREE as you suggest, or are there more issues?

I can fix the first two issues when I modify FLATCC_ALIGNED to FLATCC_ALIGNED_FREE, and add a condition before call `flatcc_builder_aligned_free(flatbuffer);` such as 
```
if (flatbuffer) {
     flatcc_builder_aligned_free(flatbuffer); 
}
```
the problems (segment fault) go away.

But the last issue still occurs. The moster_test alwasys fail which report:
```
"monster_test" start time: May 09 19:51 CST
Output:
----------------------------------------------------------
table with empty struct:
running debug monster test
empty member not available
TEST FAILED
00000000  08 00 00 00 4d 4f 4e 53  fc ff ff ff 04 00 04 00  |....MONS........|
<end of output>
Test time =   0.00 sec
----------------------------------------------------------
Test Failed.
"monster_test" end time: May 09 19:51 CST
"monster_test" time elapsed: 00:00:00
----------------------------------------------------------

```

and I think it is a different issue.

**Comment by mikkelfj** [comment]
If fixed the define and null check in this commit - with that all tests pass using the FLATCC_USE_GENERIC_ALIGNED_ALLOC flag

https://github.com/dvidelabs/flatcc/commit/6c0a4921a0a612be8f8ad7ee10c5e2d1dfb35610

Does it work for you now? Perhaps your null pointer check was in the wrong place.

**Comment by charleszhangjie** [comment]
> If fixed the define and null check in this commit - with that all tests pass using the FLATCC_USE_GENERIC_ALIGNED_ALLOC flag
> 
> [6c0a492](https://github.com/dvidelabs/flatcc/commit/6c0a4921a0a612be8f8ad7ee10c5e2d1dfb35610)
> 
> Does it work for you now? Perhaps your null pointer check was in the wrong place.

Your fix is OK.  I put null pointer check in test code because I found similar codes in other test codes.
Of course, it is better to put this check in `__flatcc_aligned_free`

it does work now except the NO.3 monster_test, does it pass in your environment?

**Comment by mikkelfj** [comment]
yes, all my tests pass, but maybe by accident?

It could be because the test code uses aligned_free instead of flatcc_builder_aligned_free, but I haven't investigated.

**Comment by mikkelfj** [comment]
no, the tests seems to be using the right free call.

**Comment by charleszhangjie** [comment]
> yes, all my tests pass, but maybe by accident?
> 
> It could be because the test code uses aligned_free instead of flatcc_builder_aligned_free, but I haven't investigated.

I ran the monster_test_d,  it reached to line 333, and failed (my compiler is gcc-4.8.5)
https://github.com/dvidelabs/flatcc/blob/6c0a4921a0a612be8f8ad7ee10c5e2d1dfb35610/test/monster_test/monster_test.c#L325-L335

Both `aligned_free` and ` flatcc_builder_aligned_free` will cause this. 
I wonder why I get different result with you

**Comment by mikkelfj** [comment]
Not sure, but empty structs are not valid in C, but gcc has an exception. Flatcc defines empty structs with an extra unused fields, or as void, depending on where it is used. I actually looked into this yesterday and I think flatcc breakes with empty structs that are members of another struct (void not a valid field type).

So it could be related to that somehow, more than aligned alloc issues. But I not sure how.

**Comment by mikkelfj** [comment]
Can you provide the full hexdump of the buffer that fails?

**Comment by mikkelfj** [comment]
Oh, you already did. It really is empty.

**Comment by charleszhangjie** [comment]
> Not sure, but empty structs are not valid in C, but gcc has an exception. Flatcc defines empty structs with an extra unused field, or as void, depending on where it is used. I actually looked into this yesterday and I think flatcc breaks with empty structs that are members of another struct (void not a valid field type).
> 
> So it could be related to that somehow, more than aligned alloc issues. But I am not sure how.
> 
> (I use clang on OS-X, but CI builds use gcc, clang and msvc, but without the generic alloc flag)

I update the code to the newest and all my tests pass too.
Maybe something was wrong but it has been fixed.

**Comment by mikkelfj** [comment]
Strange. The buffer you provided has the vtable <04 00 04 00> This means that the vtable size is 4 bytes (just the header and nothing more), and the table content is 4 bytes (just the vtable pointer and nothing more). This means the buffer is correct. Because the struct is empty, the table should not be any larger, but the vtable should have a entry for the empty struct pointing to offset 4 in the table (the end). Since structs to not have default values, it cannot skip this vtable entry and this is why the test fails.

I'm not sure how you managed to create that buffer. It is not simply a truncation because then the vtable header should say the vtable should be larger, and verify should also fail.

**Comment by mikkelfj** [comment]
Perhaps it is just unreliable code because of other things going wrong and a clean rebuild fixes that?

**Comment by charleszhangjie** [comment]
> Perhaps it is just unreliable code because of other things going wrong and a clean rebuild fixes that?

Yes, I made a mistake, I used unreliable code because I modified some other  things in my branch.
A clean rebuild is OK
Thank you very much!

**Comment by mikkelfj** [comment]
Note that scripts/test.sh is supposed to do a complete clean for that reason.
