### ISSUE TITLE
"make install" to a custom directory

### ISSUE THREAD

**Issue by tonyhutter** [dvidelabs/flatcc#121]
Normally with a cmake project you can do:
```
cmake -DCMAKE_INSTALL_PREFIX=install/to/this/directory
make
make install
```
...and it will install binaries, headers, and libs to `install/to/this/directory`.  I don't see a way to do this with flatcc, but maybe I'm missing something obvious.  How would I go about installing to a custom directory?

**Comment by mikkelfj** [comment]
I'm not a CMake expert on what is customary. By default flatcc installs into a local bin and lib dir, but there are variables that can be overridden. If you can come up with a more correct way of achieving this without breaking current behaviour please do.

The following PR may be relevant to this discussion: https://github.com/dvidelabs/flatcc/pull/109

**Comment by mikkelfj** [comment]
It seems that AUR packages uses install prefix:

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=flatcc

```
build() {
  cd "${srcdir}/${pkgname}-${pkgver}"

  mkdir -p build && cd build

  cmake \
    -DBUILD_SHARED_LIBS=on \
    -DFLATCC_ALLOW_WERROR=off \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DFLATCC_INSTALL=on \
    ..

  make
}
```

**Comment by tonyhutter** [comment]
Thanks, that answers my question.  Closing issue.
