### ISSUE TITLE
Macro produces declaration incompatible with GCC -Wstrict-prototypes option

### ISSUE THREAD

**Issue by rkennedy** [dvidelabs/flatcc#122]
We use GCC's `-Wstrict-prototypes` option in our project. However, it leads to issue a diagnostic about one of the declarations produced by the `__flatcc_basic_scalar_accessors_impl` macro:

```
/work/flatcc/include/flatcc/flatcc_endian.h:80:41: error: function declaration isn’t a prototype [-Werror=strict-prototypes]
  __flatcc_define_basic_scalar_accessors(flatbuffers_, flatbuffers_endian)
                                         ^
/work/flatcc/include/flatcc/flatcc_accessors.h:13:22: note: in definition of macro ‘__flatcc_basic_scalar_accessors_impl’
 static inline size_t N ## __size()                                          \
                      ^
/work/flatcc/include/flatcc/flatcc_accessors.h:70:1: note: in expansion of macro ‘__flatcc_define_integer_accessors_impl’
 __flatcc_define_integer_accessors_impl(N, T, W, E)
 ^
/work/flatcc/include/flatcc/flatcc_accessors.h:76:1: note: in expansion of macro ‘__flatcc_define_integer_accessors’
 __flatcc_define_integer_accessors(NS ## TN, T, W, E)
 ^
/work/flatcc/include/flatcc/flatcc_accessors.h:82:1: note: in expansion of macro ‘__flatcc_define_basic_integer_accessors’
 __flatcc_define_basic_integer_accessors(NS, char, char, 8, E)               \
 ^
/work/flatcc/include/flatcc/flatcc_endian.h:80:2: note: in expansion of macro ‘__flatcc_define_basic_scalar_accessors’
  __flatcc_define_basic_scalar_accessors(flatbuffers_, flatbuffers_endian)
  ^
```

The problem is that `static inline size_t N ## __size()` _looks_ like it defines a zero-argument function, but that's only in C++. In C, that declares a function taking any number of arguments, which probably isn't the intention.

The fix is to add `void` in the middle: `static inline size_t N ## __size(void)`. (C++ will continue to recognize it as a zero-argument function, just as before.)

**Comment by mikkelfj** [comment]
I'll admit I have not carefully guarded against this problem, but I do not understand why the source is incorrect here.

The function is a definition, not a declaration (i.e. prototype with empty args). In C it is valid to have a function definition with empty args.

As an aside, the __size() can probably be replaced with a sizeof() call now that FlatBuffers no longer support empty structs.

**Comment by mikkelfj** [comment]
For reference:
https://softwareengineering.stackexchange.com/a/287002

At least for C11:

> An empty list in a function declarator that is part of a definition of that function specifies that the function has no parameters.

**Comment by mikkelfj** [comment]
Clang raises no errors or warnings with -Wstrict-prototypes

While I'd be happy to fix this issue, the flatcc policy towards gcc warnings is moving towards disabling offending warnings in CMake, because gcc is starting to make warnings as errors that are near impossible to honour in portable code and because it keeps breaking code with every new release for no good reason. See also #120.

**Comment by mikkelfj** [comment]
Could you please check commit cd97b11

This should fix __size() and also _get_len() in runtime library and generated code.

I enabled -Wstrict-prototype for clang but not for gcc because there might be code in the flatcc compiler that gcc would happily break which I am not inclined to deal with considering that it is perfectly valid C11 code. This passes all builds  that I have access to.

**Comment by rkennedy** [comment]
I see you're right about it being a definition. I wasn't aware of the "declaration as definition" exception to the "empty parameter list" rule, but I must also admit I didn't look very closely at the supposedly offending code because I've encountered the same warning so many other times for legitimate cases that I thought I already understood the issue.

Your changes look good to me.

I thought the exception to the rule might be something new for C11, which my organization doesn't use yet, but I see identical wording in the C90 and C99 standards, so it seems GCC's warning is just plain wrong in this case. That's ... frustrating. Thanks for handling it so graciously.
