### ISSUE TITLE
verifier: generate function is missing

### ISSUE THREAD

**Issue by DanielHartung** [dvidelabs/flatcc#123]
i want to verifiy the received table via the onboard verification function:
flatcc_verify_field()

I generated the flatbuffer for C language.
The problem is that the prototype of the verify function is available in header flatcc_verifier.h but there is no function body.

Is the function body generation implemented for C?

**Comment by mikkelfj** [comment]
I'm not sure I quite follow. As an example consider the following generated verifier:

https://github.com/dvidelabs/flatcc/blob/master/include/flatcc/reflection/reflection_verifier.h

Ignore `reflection` it is just some schema `reflection.fbs` that is already generated and checked in.

The verifier only verifies tables and structs. These are the only things that can be at the root of buffer. But the table verifiers are also not called directly under normal operation. Instead you call the `_as_root` version. This function is a thin helper to do additional work of reading and verifying the buffer header first. For example:

`reflection_Schema_verify_as_root`

A table verifier verifies fields, but there is no no generated field verifier. There is only one library function `flatcc_verify_field` that is called with different parameters. This function is not something you should call directly unless you really know what you are doing. It is defined in

https://github.com/dvidelabs/flatcc/blob/master/src/runtime/verifier.c

and its prototype is found in

https://github.com/dvidelabs/flatcc/blob/master/include/flatcc/flatcc_verifier.h

**Comment by mikkelfj** [comment]
Maybe your problem is just that you need to link with the src/runtime/verifier.c code?

**Comment by DanielHartung** [comment]
okey i copied the verifier.c into my project and now the code compiles.

i get allways the return code 2 of the function shema_verify_as_root(buffer, buffer_size)

my buffer is 100k big but the table i load is allways smaller so i give the verifier_as_root a pointer to the beginning of the buffer and the size of the loaded table.

**Comment by mikkelfj** [comment]
Code 2 is probably identifier_mismatch - you can see be calling `flatcc_verify_error_string(code)`

This is a common problem, especially if your buffer is created elsewhere. Not all tools support identifiers. If you do not are about the identifier being correct you can specify a null identifier to the verifier:

mytable_verify_as_root_with_identifier(buf, size, 0).

If this works you may have to use similar with_identifier calls to read the buffer.

**Comment by mikkelfj** [comment]
I added a section to the README:

https://github.com/dvidelabs/flatcc#trouble-shooting

**Comment by DanielHartung** [comment]
Thanks for the hint.

with the verifier "mytable_verify_as_root_with_identifier(buf, size, 0)" it works and i found failures in the table.

Thanks for help.
