### ISSUE TITLE
Unable to compile programs using flatcc

### ISSUE THREAD

**Issue by alihoseiny** [dvidelabs/flatcc#124]
I compiled flatcc on my machine (using Fedora 30) and I moved **flatcc** directory in the *include* directory to my `/usr/include` directory and moved the files in the *lib* directory to the `/usr/lib` directory. But Unfortunately, I can not compile my code (That works with flatc) or your example in the *monster* directory.

The error that I get on compile time is:

```/usr/bin/ld: CMakeFiles/flatbuffer.dir/main.c.o: in function `flatcc_builder_refmap_find':
/usr/include/flatcc/flatcc_builder.h:691: undefined reference to `flatcc_refmap_find'
/usr/bin/ld: CMakeFiles/flatbuffer.dir/main.c.o: in function `flatcc_builder_refmap_insert':
/usr/include/flatcc/flatcc_builder.h:704: undefined reference to `flatcc_refmap_insert'
/usr/bin/ld: CMakeFiles/flatbuffer.dir/main.c.o: in function `flatbuffers_string_clone':
/home/mohammadreza/CLionProjects/flatbuffer/flatbuffers_common_builder.h:668: undefined reference to `flatcc_builder_create_string'
/usr/bin/ld: CMakeFiles/flatbuffer.dir/main.c.o: in function `SimpleRequest_start':
/home/mohammadreza/CLionProjects/flatbuffer/test_builder.h:27: undefined reference to `flatcc_builder_start_table'
/usr/bin/ld: CMakeFiles/flatbuffer.dir/main.c.o: in function `SimpleRequest_end':
/home/mohammadreza/CLionProjects/flatbuffer/test_builder.h:27: undefined reference to `flatcc_builder_check_required'
/usr/bin/ld: /home/mohammadreza/CLionProjects/flatbuffer/test_builder.h:27: undefined reference to `flatcc_builder_end_table'
/usr/bin/ld: CMakeFiles/flatbuffer.dir/main.c.o: in function `ComplexRequest_start':
/home/mohammadreza/CLionProjects/flatbuffer/test_builder.h:32: undefined reference to `flatcc_builder_start_table'
/usr/bin/ld: CMakeFiles/flatbuffer.dir/main.c.o: in function `ComplexRequest_end':
/home/mohammadreza/CLionProjects/flatbuffer/test_builder.h:32: undefined reference to `flatcc_builder_check_required'
/usr/bin/ld: /home/mohammadreza/CLionProjects/flatbuffer/test_builder.h:32: undefined reference to `flatcc_builder_end_table'
/usr/bin/ld: CMakeFiles/flatbuffer.dir/main.c.o: in function `Request_start':
/home/mohammadreza/CLionProjects/flatbuffer/test_builder.h:37: undefined reference to `flatcc_builder_start_table'
/usr/bin/ld: CMakeFiles/flatbuffer.dir/main.c.o: in function `Request_end':
/home/mohammadreza/CLionProjects/flatbuffer/test_builder.h:37: undefined reference to `flatcc_builder_check_required'
/usr/bin/ld: /home/mohammadreza/CLionProjects/flatbuffer/test_builder.h:37: undefined reference to `flatcc_builder_end_table'
/usr/bin/ld: CMakeFiles/flatbuffer.dir/main.c.o: in function `SimpleRequest_value_clone':
/home/mohammadreza/CLionProjects/flatbuffer/test_builder.h:71: undefined reference to `flatcc_builder_table_add_copy'
/usr/bin/ld: CMakeFiles/flatbuffer.dir/main.c.o: in function `ComplexRequest_value_clone':
/home/mohammadreza/CLionProjects/flatbuffer/test_builder.h:92: undefined reference to `flatcc_builder_table_add_copy'
/usr/bin/ld: CMakeFiles/flatbuffer.dir/main.c.o: in function `ComplexRequest_description_add':
/home/mohammadreza/CLionProjects/flatbuffer/test_builder.h:93: undefined reference to `flatcc_builder_table_add_offset'
/usr/bin/ld: CMakeFiles/flatbuffer.dir/main.c.o: in function `Request_req_add':
/home/mohammadreza/CLionProjects/flatbuffer/test_builder.h:116: undefined reference to `flatcc_builder_table_add'
/usr/bin/ld: /home/mohammadreza/CLionProjects/flatbuffer/test_builder.h:116: undefined reference to `flatcc_builder_table_add_offset'
/usr/bin/ld: CMakeFiles/flatbuffer.dir/main.c.o: in function `Request_temp_clone':
/home/mohammadreza/CLionProjects/flatbuffer/test_builder.h:119: undefined reference to `flatcc_builder_table_add_copy'
/usr/bin/ld: CMakeFiles/flatbuffer.dir/main.c.o: in function `RequestUn_union_verifier':
/home/mohammadreza/CLionProjects/flatbuffer/test_verifier.h:19: undefined reference to `flatcc_verify_union_table'
/usr/bin/ld: /home/mohammadreza/CLionProjects/flatbuffer/test_verifier.h:20: undefined reference to `flatcc_verify_union_table'
/usr/bin/ld: CMakeFiles/flatbuffer.dir/main.c.o: in function `SimpleRequest_verify_table':
/home/mohammadreza/CLionProjects/flatbuffer/test_verifier.h:28: undefined reference to `flatcc_verify_field'
/usr/bin/ld: CMakeFiles/flatbuffer.dir/main.c.o: in function `ComplexRequest_verify_table':
/home/mohammadreza/CLionProjects/flatbuffer/test_verifier.h:55: undefined reference to `flatcc_verify_field'
/usr/bin/ld: /home/mohammadreza/CLionProjects/flatbuffer/test_verifier.h:56: undefined reference to `flatcc_verify_string_field'
/usr/bin/ld: CMakeFiles/flatbuffer.dir/main.c.o: in function `Request_verify_table':
/home/mohammadreza/CLionProjects/flatbuffer/test_verifier.h:83: undefined reference to `flatcc_verify_union_field'
/usr/bin/ld: /home/mohammadreza/CLionProjects/flatbuffer/test_verifier.h:84: undefined reference to `flatcc_verify_field'
collect2: error: ld returned 1 exit status```

Also I tried `gcc main.c -o main.o -I/usr/include /usr/lib/libflatcc.a` command, But I still get the same error.

I hope you can help me in solving this issue.

**Comment by mikkelfj** [comment]
Did you resolve the problem? What was the issue?

**Comment by mtrzas** [comment]
I have the same problem but I couldn't solve it.
My CMakeLists.txt looks like this:

`project(TestFlatCC C)

set(CMAKE_C_STANDARD 11)


add_executable(TestFlatCC main.c lib/libflatccrt.a)

target_include_directories(TestFlatCC PUBLIC
        $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include/>
        )`

I would like to ask for help :)

**Comment by mtrzas** [comment]
I forgot this:

`link_directories(${CMAKE_SOURCE_DIR}/lib)`

**Comment by mtrzas** [comment]
Thank you for your answer and for the information!

When I include the library in the right way, it works!
