### ISSUE TITLE
Undefined function references even when I set include path

### ISSUE THREAD

**Issue by bturner1273** [dvidelabs/flatcc#132]
(Windows 10 powershell)
So I have flatcc built and on my path. I put it in the same directory as my .fbs file and my .c test file:
![image](https://user-images.githubusercontent.com/32464706/67954632-a792f300-fbc7-11e9-9c84-6691179b7eb7.png)

I call ***flatcc -a Car.fbs*** and 5 files are generated:
![image](https://user-images.githubusercontent.com/32464706/67954784-e1fc9000-fbc7-11e9-96e2-246beb79b5b4.png)

This is my .fbs file:
![image](https://user-images.githubusercontent.com/32464706/67956884-276e8c80-fbcb-11e9-833a-ff2a5fc9c3a5.png)

This is my c code:
```c
#include "Car_builder.h"
#include "flatbuffers_common_builder.h"
#include <time.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#undef ns
#define ns(x) FLATBUFFERS_WRAP_NAMESPACE(Test, x)

struct Car {
    char* make;
    char* model;
    int year;
};

struct Car getRandomCar () { 
    struct Car randomCar;
    int a = rand();
    if (a % 2 == 0) {
        strcpy(randomCar.make, "Ford");
        strcpy(randomCar.model, "Focus");
    } else {
        strcpy(randomCar.make, "Toyota");
        strcpy(randomCar.model, "Corolla");
    }
    randomCar.year = rand();
    return randomCar;
}

void printCar (struct Car car) {
    printf("---------------------------\nCar:\nMake: %s\nModel: %s\nYear: %d\n---------------------------", 
        car.make, 
        car.model, 
        car.year
    );
}

int main (void) {
    srand(time(NULL));
    struct Car car = getRandomCar();

    flatcc_builder_t builder, *B;
    B = &builder;
    flatcc_builder_init(B);
    uint8_t *buf;
    size_t size;

    flatbuffers_string_ref_t make = flatbuffers_string_create_str(B, car.make);
    flatbuffers_string_ref_t model = flatbuffers_string_create_str(B, car.model);
    
    ns(Car_start_as_root(B));
    ns(Car_name_add(B, make));
    ns(Car_model_add(B, model));
    ns(Car_year_add(B, car.year));
    ns(Car_end_as_root(B));
    buf = flatcc_builder_finalize_buffer(B, &size);

    //just print the buffer to see what happened
    for (size_t i = 0; i < size; i++) {
        printf("buf[%d]: %02X", i, buf[i]);
    }

    free(buf);
    return 0;
}
```

When I run ***gcc flatbuffers_test.c*** I get:
![image](https://user-images.githubusercontent.com/32464706/67955910-a82c8900-fbc9-11e9-9cd8-15e99ae09541.png)

When I run ***gcc flatbuffers_test.c -o flatbuffers_test -I flatcc/include flatcc/lib/flatcc_d.lib*** I get:
![image](https://user-images.githubusercontent.com/32464706/67956280-36a10a80-fbca-11e9-8d95-5d0b00913e9f.png)

Any suggestions on what I can do to get this running correctly? I built the library in visual studio using the cmake template to open the CMakeLists.txt as a solution, but now I want to run my code that interacts with the built library in gcc.

**Comment by bturner1273** [comment]
I have also tried **gcc flatbuffers_test.c -I flatcc\include** by itself with no -o flag and no library inclusion at the end and it gives the same results as the last image

**Comment by mikkelfj** [comment]
Try  replacing `flatcc/include flatcc/lib/flatcc_d.lib` with ` flatcc/include flatcc/lib/flatrtcc_d.lib`

The libflatcc is the compiler and does not necessarily support everything you need for the runtime but libflatccrt does.

**Comment by mikkelfj** [comment]
I updated the "Trouble Shooting" section with this info. Assuming the above fixes your problem, you are not the first to encounter this issue.

https://github.com/dvidelabs/flatcc#trouble-shooting

**Comment by bturner1273** [comment]
![image](https://user-images.githubusercontent.com/32464706/67966960-2e9d9680-fbdb-11e9-886d-45137b0fce85.png)

After trying that I got the same output

**Comment by mikkelfj** [comment]
Try reordering to so the library appears first.

**Comment by bturner1273** [comment]
![image](https://user-images.githubusercontent.com/32464706/67967256-a8ce1b00-fbdb-11e9-924d-5a68c54c653e.png)

that gives me the same issue as not setting my include path. Would it help if I included a zip?

**Comment by bturner1273** [comment]
[flatbuffers_test.zip](https://github.com/dvidelabs/flatcc/files/3794912/flatbuffers_test.zip)

^^zip of project

What is wrong with the -I flag?

**Comment by mikkelfj** [comment]
zip: I don't have Windows and although you use gcc I'm not sure that is sufficient to help.

I'm not totally sure about the linking order issue but the -I flag is easy: it is placed before include directories, not before libraries.

You probably need the formula:

    gcc <library>.a -I <include-path> <myfile.c>

You specify the library on the command line without any linker flags and I think that is OK, but it may require you to place the .c file after the library. I have a `setup.sh` script that can help you if you run shell shell scripts. https://github.com/dvidelabs/flatcc#introduction

**Comment by mikkelfj** [comment]
No, it should be OK to have the library later, at least on MacOS
This is the build command the setup.sh script generates for test projects:

https://github.com/dvidelabs/flatcc/blob/9b06cb97b7f37c330c18120fbde90b78b90d1879/scripts/_user_build.in#L32

**Comment by mikkelfj** [comment]
Arrh - it's because you fix one issue and then have another and I didn't pay attention.

Your issue is now that you also need your generated flatbuffers files in the include path.

**Comment by bturner1273** [comment]
Oh sorry about that didn't realize the library needed to come before the include. I tried that and it is still giving me the same issue:
![image](https://user-images.githubusercontent.com/32464706/67968025-06169c00-fbdd-11e9-96cd-94ae46a46d5e.png)

Also my build script didn't work. Also from your last comment so I need to add ./generated to the include path as well like **-I flatcc/generated flatcc/include** ?

**Comment by mikkelfj** [comment]
I looked at your zip file and replaced the flatcc dir with my own so I have the libraries compiled for my platform.

`gcc -I ./flatcc/include ./flatcc/lib/libflatccrt_d.a flatbuffers_test.c`

This compiles with a single warning in flatbuffers_test.c and segfaults when executed.

**Comment by mikkelfj** [comment]
> Oh sorry about that didn't realize the library needed to come before the include.

It doesn't, it was just speculation. I think your library is not built correctly for some reason.
flatcc is compiled for Windows via continous integration using the MVSC compiler. It seems that your setup with gcc on Windows somehow doesn't work, but I cannot tell what it is.

You can also compile directly with src/runtime/builder.c and other necessary files.

**Comment by mikkelfj** [comment]
> Also my build script didn't work. Also from your last comment so I need to add ./generated to the include path as well like -I flatcc/generated flatcc/include ?

I deleted that comment, but you saw it anyway - that is usually the case, but it is not your problem here because you have everything in project root.

**Comment by mikkelfj** [comment]
And just for completeness: `-I flatcc/generated flatcc/include` would have to be `-I flatcc/generated -I flatcc/include`, that is `-I` must be repeated - assuming your generated code is in `flatcc/generated` that is for you to decide.

**Comment by siliangQ** [comment]
Did you figure out how to solve the problem? I haave the same issue when I try to build my c application with flatbuffer.

**Comment by mikkelfj** [comment]
@siliangQ I'd like to help, but without further information, all I can say is to repeat: make sure you are using the same version of the library and flatcc compiler used to generate the code, and use the same compiler for the library and end user code.

**Comment by siliangQ** [comment]
@mikkelfj Thank you so much for your reply. That is a good direction. I double-checked the library and compiler and found out the library I linked with my application is mismatched with the flatcc compiler. So I use the following command to get the problem resolved.
`gcc -o main.c <absolution path to static library>`
Now it is compiled successfully.

**Comment by mikkelfj** [comment]
I'm glad it worked for you.
