### ISSUE TITLE
Buffer size is huge for 3 string table

### ISSUE THREAD

**Issue by bturner1273** [dvidelabs/flatcc#133]
I have a table with 3 strings in it that are very short:

This is my schema:
![image](https://user-images.githubusercontent.com/32464706/68784301-5690ef00-060a-11ea-8f96-2fbcc21151f0.png)

This is my code to serialize the "APNSettings" table:
![image](https://user-images.githubusercontent.com/32464706/68784094-087beb80-060a-11ea-9c32-c2ca8620a94f.png)

**So testing this I load the settings.apn struct with**
```c
setting_t test;
uint8_t buffer[1024];
memcpy(test.apn.apn, "apn", 3);
memcpy(test.apn.username, "username", 8);
memcpy(test.apn.password, "password", 8);
size_t size = shadow_encode_apn_settings(test, buffer);
```
**The size that is returned is equal to 3764:** this seems way too large am I right?

**Comment by mikkelfj** [comment]
The size does sound excessive. That is likely the input data. You copy 8 bytes to a struct I don't know the format of, and you do not make sure the string is terminated. You can use create_str_n for a purpose.

The buffer is also returned incorrectly. You either need `uint8_t **buffer` and assign `*buffer = finalize ...` and free it later with a flacc call, or or you must use another finalize call that takes a buffer as argument and the maximum capacity.

**Comment by bturner1273** [comment]
Thank you for the help! I replaced the create_str calls with create_strn and it made the size reasonable. Also fixed the buffer return!

**Comment by mikkelfj** [comment]
you are welcome!
