### ISSUE TITLE
JSON parsing fails with deprecated fields

### ISSUE THREAD

**Issue by Himbeertoni** [dvidelabs/flatcc#142]
If a flatbuffer field gets annotated with "(deprecated)" the JSON parsing of that table fails with error "unknown symbol". Unfortunately, the error reporting is not more detailed. Maybe it has to do with the fact that the table is part of a union?
I'm on 6c5a624867d6132c500366f4134c52bf372700a1, but the git log does not indicate any fix in the current version.

**Comment by mikkelfj** [comment]
This isn't a bug. Deprecated fields are not considered valid data and an error message helps to avoid getting garbage data. A deprecated field only exists to keep binary compatible with old buffers.

If you have JSON data specific to an old version, you can enable a runtime flag to ignore unknown symbols: flatcc_json_parser_f_skip_unknown

This flag will also ignore any other unknown, or misspelled symbols, so the error reporting will be reduced.

Here is a test case that uses this flag:

https://github.com/dvidelabs/flatcc/blob/401cee0d0840dee8ab2c257af9e928049a17b05a/test/json_test/test_json.c#L204-L206

**Comment by mikkelfj** [comment]
I added a note on this in the README: https://github.com/dvidelabs/flatcc/commit/484f13c6c1995ea2a2a77535e16cd0de76d8aabb

**Comment by Himbeertoni** [comment]
Thank you, adding the flag fixes my issue.

**Comment by mikkelfj** [comment]
Thanks for letting me know.
