### ISSUE TITLE
How to compile string

### ISSUE THREAD

**Issue by kiwidoggie** [dvidelabs/flatcc#144]
```struct DbgProcessLimited
{
    processId:int32;
    name:string;
    threads:[DbgThreadLimited];
}```

This is in the .fbs file, and when I use `flatcc -w -v debugger.fbs` it returns an error `debugger.fbs:101:5: error: 'name': struct member member can only be of struct scalar, or fixed size scalar array type`

Are strings not supported? or do I need to use [uint8_t:size]?

**Comment by mikkelfj** [comment]
Yes, you must use fixed length arrays as you suggest. This is a relatively new feature so not all languages support it yet, I think.

FlatCC also supports `[char:size]` but char is not supported elsewhere (it is just to avoid typecasts when data is used in C functions).

Structs are always self-contained fixed size memory blocks so they cannot embed a string or reference a string.

**Comment by kiwidoggie** [comment]
thanks a lot 😊
