### ISSUE TITLE
Is there vcpckg for flatcc?

### ISSUE THREAD

**Issue by ademyankov** [dvidelabs/flatcc#148]

**Comment by mikkelfj** [comment]
No, there is a MSVC build via CMake, perhaps you can make something out of that?

**Comment by ademyankov** [comment]
Yeah, thank you. I can build Linux and MSVS manually with no issue. The problem is a different one. 

Even though flatcc build system is CMake, but for some weird reason, it doesn't comply to a normal CMake way of building things! And now flatcc cannot be used with a standard CMake FetchContent way.

**Comment by mikkelfj** [comment]
If you have any suggestions on how to improve the CMake build, feel free to come with suggestions as long as it doesn't fundamentally break the experience for other users.

**Comment by ademyankov** [comment]
Well, the suggestion is very simple, do not reinvent the wheel, follow the accepted CMake build patter, that everyone uses.

Because, what happens, is that actually, the current build mechanism breaks the experience for all users. Let me tell you what I mean. I am new to CMake and I expect (naturally) to do the following:
```
git clone https://github.com/dvidelabs/flatcc.git
cd flatcc
mkdir build
cd build
cmake ..
make
```
That's it. Done!
Then, If I want to use flatcc in my CMake project, I can simply do 2 lines of code.
```
FetchContent_Declare(
  flatcc
  GIT_REPOSITORY https://github.com/dvidelabs/flatcc.git
  GIT_TAG        master
)
FetchContent_MakeAvailable(flatcc)
```
Done! I don't have to do any extra work or worry about the dependencies.

Now, since flatcc doesn't follow the accepted CMake build pattern I have a bunch of headaches!
1. FetchContent doesn't work anymore. Now, I have to write an extra 20 lines of code in order to have flatcc as a dependency (and that code doesn't handle debug and release configurations yet).
```
# FLATCC Library dependencies ------------------------------------------------
if (MSVC)
    set(FLATCC_LIB_ROOT "$ENV{FLATCC_ROOT}/lib/Debug")
elseif(UNIX)
    set(FLATCC_LIB_ROOT "$ENV{FLATCC_ROOT}/lib")
endif()

find_path(FLATCC_INCLUDE NAMES flatcc/flatcc.h HINTS "$ENV{FLATCC_ROOT}/include")
find_library(FLATCC_LIB NAMES flatccrt flatccrt_d HINTS ${FLATCC_LIB_ROOT})

message("-- FLATCC LIBRARY:")
message(STATUS "  FLATCC_INCLUDE=${FLATCC_INCLUDE}")
message(STATUS "  FLATCC_LIB=${FLATCC_LIB}")
message("--")

if(NOT FLATCC_INCLUDE OR NOT FLATCC_LIB)
    message(FATAL_ERROR "Unable to setup FLATCC library dependencies."
    "Make sure environment variable FLATCC_ROOT is set and valid")
endif()
# ----------------------------------------------------------------------------
```
2. Now, the user of my code has to manage the flatcc library him/her self! It needs to be git clone first, then build, then FLATCC_ROOT environment variable needs to be set up.

Don't get me wrong, men, it's not like I am bitching here. I really appreciate flatcc a free, open-source library. It's a great library. But why the hack it doesn't follow CMake convention? Do you see my point?

**Comment by mikkelfj** [comment]
I don't understand why that would be a problem? 

You can build flatcc exactly as you describe. The build scripts are just to help get things going. And for development, scripts/test.sh ensures the build is always completely clean and that both debug and release builds are executed and test cases run. scripts/build.sh runs builds without cleaning first. And you can configure if you want to use make or ninja builds without having to enter it on the CMake command line every time. But each of these modes are just creating a directory and executing a CMake command.

One thing that is perhaps slightly unconventional for CMake is the ./lib and /.bin directories created outside the build directory, but this is common for Make builds and makes it easy to find the binaries.

**Comment by mikkelfj** [comment]
Is the issue that you want the binaries located in the CMake instead of the bin and lib directory at root, or in addition to this location?

**Comment by mikkelfj** [comment]
Note that you can override the output locations:

https://github.com/dvidelabs/flatcc/blob/e33df1aebb460277e71e7b65fdd82f3f0b27d94a/CMakeLists.txt#L325-L330

**Comment by ademyankov** [comment]
I am not sure anymore how to describe it. I (as a consumer of the library) don't really care about where the binary goes, whether it is bin, lib, out, or whatever, where the headers are, etc... I just want to "say" I need this lib as my dependency and be done with it.

I attached a tiny sample app. This is, what I consider, a standard cmake approach and flatcc does not work with it, where other libs, like googletests does.
[hello_flatcc.tar.gz](https://github.com/dvidelabs/flatcc/files/4707413/hello_flatcc.tar.gz)

You will notice in the cmake that I checkout master (which is kinda pointless since there is no attachment to a specific version) branch. If I try to use a known version tag 'v0.6.0' then it doesn't even build (it builds flatcc.a but no flatccrt.a).

**Comment by mikkelfj** [comment]
Sorry, but I can't really help here. I am not using CMake FetchContent, I am not a CMake expert, and I don't use Windows (requires a complex setup to test).

Furthermore, a general flatcc distribution cannot execute with just one standard CMake command because you must decide between release or debug and static or shared libraries, so at the very least FetchContent must be able to set arguments to CMake specific to the users preference. If you do that, and additionally specify include, lib and bin directories in you own project, I don't see why it shouldn't work. But again, I am not familiar with FetchContent.

So, if you want to improve on this, you will need to recruit some CMake expertise and suggest some changes.

Here is how some build systems use flatcc which all build using a cmake call in their respective standard configuration after setting platform specific CMake build options:

https://github.com/Homebrew/homebrew-core/blob/master/Formula/flatcc.rb
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=flatcc
https://git.buildroot.org/buildroot/tree/package/flatcc/flatcc.mk

Note that buildroot disables tests to avoid a C++ dependency for embedded systems, AUR configures shared libraries for Arch Linux, and HomeBrew for MacOS uses a standard cmake call but specifies Unix Make as the build engine (as opposed to Ninja build).

**Comment by ademyankov** [comment]
Yeah, I got your point. No worries man. BTW, the project builds for Linux as well, you don't need windows and VS.
Thanks for the pointers, I am gonna study those...

**Comment by ademyankov** [comment]
Ok, I finally was able to figure out how to make it work with CMake FetchContent.

Here is the solution for those who might need it.
```
set(FLATCC flatcc)
FetchContent_Declare(
    ${FLATCC}
    GIT_REPOSITORY   https://github.com/dvidelabs/flatcc.git
    GIT_TAG                 v0.6.0
)

FetchContent_GetProperties(${FLATCC})
if(NOT ${FLATCC}_POPULATED)
    FetchContent_Populate(${FLATCC})

if(UNIX)
    set(BUILD_SHARED_LIBS ON CACHE INTERNAL "Build SHARED libraries")
endif()

    set(FLATCC_TEST OFF CACHE INTERNAL "Do not build tests")
    set(FLATCC_ALLOW_WERROR OFF CACHE INTERNAL "No error on warnings")
    set(FLATCC_INSTALL OFF CACHE INTERNAL "Do not install")

    add_subdirectory(${${FLATCC}_SOURCE_DIR} ${${FLATCC}_BINARY_DIR})
endif()

include_directories(${${FLATCC}_SOURCE_DIR}/include)
```

**Comment by mikkelfj** [comment]
Glad you made it work!
