### ISSUE TITLE
Corrupted JSON parser for some field name combinations

### ISSUE THREAD

**Issue by skhoroshavin** [dvidelabs/flatcc#17]
Looks like JSON parser generator sometimes generates corrupted path for parsing _type fields. I've attached a simple repro case:
[test.fbs.txt](https://github.com/dvidelabs/flatcc/files/617888/test.fbs.txt)
[test.json.txt](https://github.com/dvidelabs/flatcc/files/617887/test.json.txt)

After lots of experiments I found that fields with length from 1 to 3, 8 to 11, etc work correctly, while lengths 4 to 7, 12 to 15 lead to nonparseable field_type. From comments in generated parser file it seems that some symbols get eaten. I tried to debug code generator, found that field dictionary is built correctly, and then something bad happens in gen_trie.

**Comment by mikkelfj** [comment]
Thanks, I'll have a look. This is good info to go by. FYI: The trie is built in levels so 8 bytes are processed at a time. The exact lengths causing problems sound strange - it could also be the relative sorting order of keys being tested and the length of their shared prefixes.

**Comment by skhoroshavin** [comment]
I've managed to reduce minimal test scheme to:

table test
{
	aaaa: string;
	aaaa12345: uint;
}
root_type test;

aaaa is read just fine, aaaa12345 is unrecognized. I think this confirms that problem is in trie generator, not unions. Relevant parts of generated code are following:

        buf = flatcc_json_parser_symbol_start(ctx, buf, end);
        w = flatcc_json_parser_symbol_part(buf, end);
        if (w == 0x6161616100000000) { /* prefix "aaaa" */
            buf += 8;
            w = flatcc_json_parser_symbol_part(buf, end);
            if ((w & 0xff00000000000000) == 0x3500000000000000) { /* "5" */
                buf = flatcc_json_parser_match_symbol(ctx, (mark = buf), end, 1);
                if (mark != buf) {

                    /* PARSE UINT */

                } else {
                    buf = flatcc_json_parser_unmatched_symbol(ctx, buf, end);
                }
            } else { /* "5" */
                buf = flatcc_json_parser_unmatched_symbol(ctx, buf, end);
            } /* "5" */
        } else { /* prefix "aaaa" */
            if ((w & 0xffffffff00000000) == 0x6161616100000000) { /* "aaaa" */
                buf = flatcc_json_parser_match_symbol(ctx, (mark = buf), end, 4);
                if (mark != buf) {

                    /* PARSE STRING */

                } else {
                    buf = flatcc_json_parser_unmatched_symbol(ctx, buf, end);
                }
            } else { /* "aaaa" */
                buf = flatcc_json_parser_unmatched_symbol(ctx, buf, end);
            } /* "aaaa" */
        } /* prefix "aaaa" */

**Comment by mikkelfj** [comment]
great work - it seems to be confused about an exact prefix match that is short than 8 bytes, and another prefix match that is exactly 8 bytes. You see the test for '5' - it should happen after testing fo the prefix aaaa1234, but the test is placed in the shorter "aaaa" prefix test.

It is likely that I confused myself between these two cases while implementing the code generation - it was quite tricky to get right, and apparently I failed at that.

**Comment by mikkelfj** [comment]
Line 3 should test against the big endian word of "aaaa124" and not the big endian word of ("aaaa"):

 if (w == 0x6161616100000000)
=>
 if (w == 0x6161616131323334) { /* prefix "aaaa1234" */


It seems the overall structure is ok, but the constants are not.

**Comment by skhoroshavin** [comment]
Thanks, at last I've found exact place where prefix was corrupted:

897:     get_dict_tag(&trie->dict[x], pos, &tag, &mask, &name, &len);  // this produces aaaa1234
906:     has_prefix_key = 0;
907:     if (a != x) { // a == 0, x == 1
908:         n = get_dict_tag(&trie->dict[x - 1], pos, &tag, &mask, &name, &len); // this overrides with aaaa
909:         if (n == 8) { // n == 4
910:             has_prefix_key = 1; // so we don't get there
911:         }
912:     }
915:     println(out, "if (w == 0x%"PRIx64") { /* prefix \"%.*s\" */",  // output aaaa
                    tag, len, name); indent();

While I understand big picture of what's going on I still don't have good enough understanding of what each piece of code is doing to make conscious changes. I can only guess that after failure at line 909 local state should be restored to aaaa1234, is it?

**Comment by skhoroshavin** [comment]
Seems like my guess was right - it fixed my issue, and tests are still passing. I'm going to add this fix into my pull request.

**Comment by mikkelfj** [comment]
OK, currently I'm debugging several different pieces of crypto stuff so I have a difficult time wrapping my head around this too, right now, so I'm inclined to take your word for it - can't get any worse suppose :)

**Comment by mikkelfj** [comment]
Umm - I just read through that function - this code is so tricky, you cannot just make a qualified guess - something else will likely break.

If I recall correctly it is operating a range [a...x ... y ... b] where x any y are both midpoints but anything between x and y are equal keys at the current trie level. Reading the next key into the tag, ([x] instead of [x-1]) might work in some tests, but risks landing on the wrong side of some test (or indeed fix it so lands right). But I'm pretty sure the code was not designed to read a tag on and discard it if length is not 8. So I need a better understanding of what is going on. You are welcome to contribute if you get a more detailed understanding.

**Comment by skhoroshavin** [comment]
As far as I understand this code first searches for first key with suffix:

            k = get_dict_suffix_len(&trie->dict[x], pos);
            while (x != b && !k) {
                ++x;
                k = get_dict_suffix_len(&trie->dict[x], pos);
            }

so that it could early out if there are no child nodes:

            if (!k) {
                /*
                 * The typical a == b single key match,
                 * or all keys that share prefix and end within
                 * the current tag range
                 */
                gen_prefix_trie(out, trie, a, b, pos);
                return;
            }

Then it gets first key with suffix:

            get_dict_tag(&trie->dict[x], pos, &tag, &mask, &name, &len);

and checks if previous key (without suffix) was in original range a..b and fills 8 bytes:

            has_prefix_key = 0;
            if (a != x) {
                n = get_dict_tag(&trie->dict[x - 1], pos, &tag, &mask, &name, &len);
                if (n == 8) {
                    has_prefix_key = 1;
                }
            }

Now if it fullfilled n==8 then it shouldn't have changed mask, name and len. But if n < 8, then those variables are certainly changed producing incorrect result. That were my thoughts behind guess I made.

**Comment by mikkelfj** [comment]
I read the code more closely - and I think you are right. The has_prefix was a later addition to the code after discovering a bug during development. Unfortunately the fix included a stupid mistake - it didn't take into account that reading a tag overwrite the already fetched tags due to pointer arguments.

You fix the undoes this mistake. But the real solution is to not make the mistake in the first place. I think it can be done by swapping the execution order. Please review and if you agree, add it to the PR. I have not run any tests myself.

            get_dict_tag(&trie->dict[x], pos, &tag, &mask, &name, &len);
            /*
             * Test for special case where prefix [pos..pos+8) is also a
             * key. We cannot branch on any tag and need a decision on
             * terminal symbol which depends the on the customizable
             * match logic. For this reason the match function ends with
             * an open else branch which can either place unmatched in,
             * or a sub trie.
             */
            has_prefix_key = 0;
            if (a != x) {
                n = get_dict_tag(&trie->dict[x - 1], pos, &tag, &mask, &name, &len);
                if (n == 8) {
                    has_prefix_key = 1;
                }
            }

=>
            /*
             * Test for special case where prefix [pos..pos+8) is also a
             * key. We cannot branch on any tag and need a decision on
             * terminal symbol which depends the on the customizable
             * match logic. For this reason the match function ends with
             * an open else branch which can either place unmatched in,
             * or a sub trie.
             */
            has_prefix_key = 0;
            if (a != x) {
                n = get_dict_tag(&trie->dict[x - 1], pos, &tag, &mask, &name, &len);
                if (n == 8) {
                    has_prefix_key = 1;
                }
            }
            get_dict_tag(&trie->dict[x], pos, &tag, &mask, &name, &len);

I think that should do it, but I haven't run any tests - it makes sense from reading the comments I wrote, while I still don't recall all the details.

**Comment by skhoroshavin** [comment]
By the way, changing order of two last pieces of code also fixes this issue and doesn't break anything:

        has_prefix_key = 0;
        if (a != x) {
            n = get_dict_tag(&trie->dict[x - 1], pos, &tag, &mask, &name, &len);
            if (n == 8) {
                has_prefix_key = 1;
            }
        }
        get_dict_tag(&trie->dict[x], pos, &tag, &mask, &name, &len);

Looks better than my previous attempt since it doesn't introduce new get_dict_tag call. And I think it shouldn't break anything - if n == 8 then both get_dict_tag calls should fill mask, name and len with same values.

**Comment by mikkelfj** [comment]
We cross posted :)

**Comment by skhoroshavin** [comment]
And had same conclusions :)

**Comment by mikkelfj** [comment]
This is excellent work - it is really not an easy piece of code to dive into and fix.

**Comment by skhoroshavin** [comment]
Thanks, but it wouldn't be possible without your help :) I've double checked everything and swapping these two pieces indeed doesn't break tests. Updating PR...
