### ISSUE TITLE
Question on attribute implementation

### ISSUE THREAD

**Issue by Dweller** [dvidelabs/flatcc#192]
I've scratching my head over the attribute implemention.   I can see flatcc parses and stores the defined attributes but apart from via the reflector I don't see any way of accessing them from within the builder or the printer.  

I guess i could use the reflector to use the fbs schema to generate a API which will allow to to check but that seems like a lot of work..   Equally I guess I could use the XSD schema file I use to create the fbs file I'm using.

I just want to add a boolean flag to each table field so I can output the FlatBuffers data to XML...  

Is there a more elegant way of implementing this I've missed?

**Comment by mikkelfj** [comment]
You may want to look at how attributes are exported for inspiration on how to implement the suggested function:

https://github.com/dvidelabs/flatcc/blob/c2158f1f1e6af8f313ee45ae394f51839c1715ba/src/compiler/codegen_schema.c#L146

**Comment by Dweller** [comment]
Thanks for that..  I'm not sure what the 'path of least resistance' is on this one..   If I an make it usefully reusable I'll certainly let you have a look.        I suspect I'l be looking first at adding it my rehashed codegen_c_xml_printer() if I can access the attribute's there that sounds good at this stage.    Time will tell I'm sure.. ;-)

**Comment by mikkelfj** [comment]
You should be able to do that. Feel free to reopen if you have anything to add.
