### ISSUE TITLE
64-bit offsets: flatcc_builder_create_buffer strange behavior

### ISSUE THREAD

**Issue by TYoungSL** [dvidelabs/flatcc#201]
I'm trying to use 64-bit offset sizes (for uoffset_t and soffset_t, adjusted config, max/min, etc.)

`flatcc_builder_create_buffer` is somehow having an additional 2<sup>32</sup> (`UINT32_MAX`+1) added to the written offset.

Somewhere before line 783-ish in _src/runtime/builder.c_.
```c
    write_uoffset(&object_offset, (uoffset_t)object_ref - buffer_base);
```

Any ideas?

**Comment by TYoungSL** [comment]
Need to change the generator to emit a definition for `FLATCC_OFFSET_SIZE`.

**Comment by mikkelfj** [comment]
OK

Note that flatcc is prepared for doing what you do, but it has never been tested, and you can expect to patch several areas of the code to get it to work. We did this for native big-endian 32-bit integets a few years ago.

The code generator also generates a namespace for common names which are currently `flatbuffers_` and `__flatbuffers_`. The idea is that a new format like large flatbuffers could have a new namespace so both can coexist. I do not suggest you take this on, but it would be needed if made into an official alternative format.
