### ISSUE TITLE
Some comments in fbs lead to uncompilable reader header

### ISSUE THREAD

**Issue by skhoroshavin** [dvidelabs/flatcc#21]
Comments like

`/////////////////////////////////////////////////////////////`
`// Some big comment`
`/////////////////////////////////////////////////////////////`

become

`/**/////////////////////////////////////////////////////////////////////`
`* ///////////////////////////////////////////////////////////////////// */`

in flatbuffer reader, which is clearly incorrect. 

I hope to look into and fix this approximately by Wednesday.

**Comment by mikkelfj** [comment]
yes, that is unfortunate

**Comment by skhoroshavin** [comment]
Fixed by #24
