### ISSUE TITLE
_portable_aligned_alloc not returning as expected when malloc is unsuccessful

### ISSUE THREAD

**Issue by edlongman** [dvidelabs/flatcc#269]
I am am compiling and running flatcc on a dsPIC using the XC16 compiler and generally having success with very minor tweaks. 

When calling `finalize_aligned_buffer` it uses the `__portable_aligned_alloc` implementation but when `malloc` cannot assign the space and it returns nullptr, the alloc does not, instead returning `4`

![image](https://github.com/dvidelabs/flatcc/assets/693456/2780b92c-4709-4f8e-b23f-b9cfd0b0a020)

Perhaps there should be a check here to see if malloc fails

**Comment by mikkelfj** [comment]
You are right, I don't know what I was thinking. Fixed in https://github.com/dvidelabs/flatcc/commit/b2125775fdec2f5a4cba7ad569ea0186adf45e70

I plan to make a release soon, so it will be in there.

**Comment by mikkelfj** [comment]
I also fixed FLATCC_ALIGNED_ALLOC which is used when you are not able to use malloc.
https://github.com/dvidelabs/flatcc/commit/6c3fe816205e25487d5320e755f91080bc57621b
