### ISSUE TITLE
parse fbs file failed when comment with utf8 characters >= 0x80

### ISSUE THREAD

**Issue by jerrrykong** [dvidelabs/flatcc#283]
I debug the program  flatcc. found in:
external/lex/luthor.c
```c
#ifndef lex_isctrl
#include <ctype.h>
#define lex_isctrl(c) ((c) < 0x20 || (unsigned char)(c) == 0x7f)
#endif
```
When the character c is utf8, it will be a negative number. This will result in being judged as a control character. Control characters are not allowed in the syntax, resulting in compilation failure.

Fix it:
```c
#ifndef lex_isctrl
#include <ctype.h>
#define lex_isctrl(c) ((unsigned char)(c) < 0x20 || (unsigned char)(c) == 0x7f)
#endif
```

**Comment by jerrrykong** [comment]
I found that is fixed. ;)

**Comment by mikkelfj** [comment]
Yes, it should be fixed here: https://github.com/dvidelabs/flatcc/issues/267
