### ISSUE TITLE
Support contiguous comments in schema enums

### ISSUE THREAD

**Issue by n3npq** [dvidelabs/flatcc#34]
Commenting out a line following a C comment in a schema enum definition causes a generation failure:
    flatcc -ad --json rpmtag.fbs
    rpmtag.fbs:372:19: error: '	': member identifier expected

The failure reproducer looks like this
    enum TAGNO:uint {
    ...
      FILESIGNATURELENGTH           = 5091, /* i */

    //  FIRSTFREE_TAG,                      /*!< internal */
    }

**Comment by mikkelfj** [comment]
Thanks. I can reproduce. It only happens because you have control characters in the C++ comment. The C comment should be irrelevant. The control character is a tab (\t), which should be accepted. I will fix this.

**Comment by mikkelfj** [comment]
The control characters were dealt with in the wrong place. Fixed, this also (at least in theory) sorts out a know misfeature stripping tabs from doc comments. Any non-space control character yields an error intentional. E.g. vertical tab is not considered a valid space.

**Comment by mikkelfj** [comment]
For the record, if there are invalid control characters in the comment, the reported error, or a similar error, are likely to show up instead of the intended control character error because comments happens everywhere, not just at statement start. This is not important enough to fix proper.
