### ISSUE TITLE
Compile error when using gcc 5.4.0 with the portable layer in C99 mode

### ISSUE THREAD

**Issue by epouponstormshield** [dvidelabs/flatcc#40]
Hello,

Using gcc 5.4.0 in C99 mode does not work.
Here is is the compile issue:

>                  from /usr/home/user/git/src/test/test.c:2:
> /usr/include/flatcc/portable/paligned_alloc.h:81:23: fatal error: mm_malloc.h: No such file or directory
> compilation terminated.
> *** Error code 1

I guess you include this file in order to make sure that posix_memalign is defined?
The problem is there is no more mm_malloc.h file shipped with gcc5.

Regards,

**Comment by epouponstormshield** [comment]
This patch fixes the issue:

--- ./include/flatcc/portable/paligned_alloc.h.orig	2017-01-21 09:52:50.000000000 +0100
+++ ./include/flatcc/portable/paligned_alloc.h	2017-03-29 19:00:59.724040000 +0200
@@ -77,7 +77,7 @@
 
 #elif PORTABLE_POSIX_MEMALIGN
 
-#ifdef __GNUC__
+#if __GNUC__ < 5
 #include "mm_malloc.h"
 #endif

**Comment by mikkelfj** [comment]
Does this mean posix_memalign is available without including mm_malloc.h?

**Comment by mikkelfj** [comment]
The change has been committed. Travis is chewing along on older gcc's now in ci-more branch and seems happy so far, but that is without C99.
https://travis-ci.org/dvidelabs/flatcc/builds/216462272

**Comment by mikkelfj** [comment]
I'm closing this, but feel free to reopen if something is still broken.

**Comment by epouponstormshield** [comment]
It works fine, thanks for your support!

**Comment by mikkelfj** [comment]
Note: I justed update paligned_alloc.h again to handle C++, but it should not have any impact on C.
