### ISSUE TITLE
hex constant parsing [question]

### ISSUE THREAD

**Issue by AndrewJDR** [dvidelabs/flatcc#54]
I noticed flatcc supports hex constant parsing:
https://github.com/dvidelabs/flatcc/commit/0f3564a69e06cabb71ff89b1b89cb64a757e9055

This is a flatcc specific feature, correct? I couldn't find reference to '0x' ... type syntax listed beside "integer constant" in the flatbuffer schema grammar document at https://google.github.io/flatbuffers/flatbuffers_grammar.html

**Comment by AndrewJDR** [comment]
I found the answer to this -- https://github.com/dvidelabs/flatcc/issues/33

**Comment by mikkelfj** [comment]
For others reading along, the answer is that hex constants in the schema was added after ensuring Googles flatc had also added support for it.

More generally: The portable libraries feature set is in itself not an indication of what FlatCC supports, and some features supported may configurable but disabled by default.
