### ISSUE TITLE
enum json printer, not static cause redefinition.

### ISSUE THREAD

**Issue by navigator117** [dvidelabs/flatcc#57]
json printer like void _XXX_print_json_enum(flatcc_json_printer_t *ctx, int8_t v) does not have "static" prefix, when include in multi files, gcc will complain multiple definition of these functions.

**Comment by mikkelfj** [comment]
Fixed, thanks.
Heads up: after the upcoming 0.4.3 release there will be a later release with significant changes to JSON parsing due to new features added.
