### ISSUE TITLE
Unclear about memory management when reading from a buffer.

### ISSUE THREAD

**Issue by pcpLiu** [dvidelabs/flatcc#62]
Hi,

I'm not clear about the memory management when I was reading a buffer.

Suppose I have read a large size of float array (and I checked that flatcc generated header returns a `const float *` representing this array) from a serialized buffer file.  Do I need to _free_ this array if I don't need to use it anymore?

**Comment by mikkelfj** [comment]
No, flatcc does not allocate anything when reading - the data stored in the buffer is directly accessible. This is why it is so fast.

However, normally you access array elements via _vec_at operations instead of using the raw pointer. This is more portable because it will also work on big endian platforms. The performance should be the same in optimized builds.

**Comment by pcpLiu** [comment]
Thanks, @mikkelfj . That's clear now.

Another question I'm not clear with allocated memory is that If I read the serialized data into a buffer I allocated and I use this buffer to create root table. Do I need to wait my all reading actions finished and then free the buffer?
Below are sample codes I wrote:
```c
    FILE *bufferFile;
    bufferFile = fopen("my_data.flatbuffer", "rb");
    // check file size
    long filelen = 0;
    fseek(bufferFile, 0, SEEK_END);         
    filelen = ftell(bufferFile);             
    rewind(bufferFile);            

    // allocate buffer and read buffer file
    char *buffer;
    buffer = (char *)malloc((filelen)*sizeof(char));
    fread(buffer, filelen, 1, bufferFile); 
    fclose(bufferFile); 

    // make root reader
    ns(MyData_table_t) my_data = ns(MyData_as_root(buffer));

    //....do some reading

    // must be here after all actions?
   free(buffer);
```

I'm not sure if I'm doing right. In the example,  there's no related code reading file to buffer.

**Comment by mikkelfj** [comment]
You can only read from the buffer while the underlying buffer memory is allocated.

Strictly speaking you need to ensure the buffer is placed in sufficiently aligned memory, but in most cases your example will work. If you look at test code you will find examples.

**Comment by mikkelfj** [comment]
You can see this example where an existing flatbuffer (generated by C++) is being read from file and then copied into aligned memory. You can avoid the copying step if you control the memory allocation while reading the file. Also, alignment is normally only an issue when working with buffer values that require alignment larger than 8 bytes, which is unusual.

https://github.com/dvidelabs/flatcc/blob/9fae97ec53152a43668659bad0061460c7640f74/test/flatc_compat/flatc_compat.c

**Comment by pcpLiu** [comment]
@mikkelfj  Thanks! Very helpful

**Comment by mikkelfj** [comment]
You are welcome!
