### ISSUE TITLE
Add various versions of clang/clang++ to the travis CI build

### ISSUE THREAD

**Issue by AndrewJDR** [dvidelabs/flatcc#79]
Various versions of clang/clang++ should probably be added to the travis.yml to catch issues like these:
https://github.com/dvidelabs/flatcc/pull/78
https://github.com/dvidelabs/flatcc/pull/59

I may do it at some point if i get some time, but it could be a while :/

In the meantime, I did do some research and found some good starting points:
* https://stackoverflow.com/questions/29312015/building-with-more-than-one-version-of-a-compiler/32127147#32127147
* https://github.com/taocpp/PEGTL/blob/master/.travis.yml

**Comment by mikkelfj** [comment]
This should probably be done on the ci-more branch where many more gcc and clang compilers are tested.

But it won't do much without a CMake C++ test project in the `test` folder that executes when `scripts/test.sh` is being run. It could perhaps just be a C++ file that includes `samples/monster/monster.c`. Such a project should be tested against v0.5.1 to verify that it indeed triggers the mentioned warnings.

**Comment by mikkelfj** [comment]
Fixed in #80 and related recent commits.
