### ISSUE TITLE
Invalid constants

### ISSUE THREAD

**Issue by csstup** [dvidelabs/flatcc#8]
include/flatcc/portable/pendian.h includes the following constants in the bswap macros:

```
#define bswap32(v)                                                          \
      ((((uint32_t)(v) << 24))                                              \
          | (((uint32_t)(v) << 8) & UINT32_C(0x00FF0000U))                  \
          | (((uint32_t)(v) >> 8) & UINT32_C(0x0000FF00U))                  \
          | (((uint32_t)(v) >> 24)))
#endif

#ifndef bswap64
#define bswap64(v)                                                          \
      ((((uint64_t)(v) << 56))                                              \
          | (((uint64_t)(v) << 40) & UINT64_C(0x00FF000000000000ULL))       \
          | (((uint64_t)(v) << 24) & UINT64_C(0x0000FF0000000000ULL))       \
          | (((uint64_t)(v) << 8) & UINT64_C(0x000000FF00000000ULL))        \
          | (((uint64_t)(v) >> 8) & UINT64_C(0x00000000FF000000ULL))        \
          | (((uint64_t)(v) >> 24) & UINT64_C(0x0000000000FF0000ULL))       \
          | (((uint64_t)(v) >> 40) & UINT64_C(0x000000000000FF00ULL))       \
```

The problem comes in that UINT32_C and UINT64_C append U and ULL to the end of the constant passed to them, so the resulting text has U and ULL appended twice:

include/flatcc/flatcc_endian.h", line 76.3: 1506-258 (S) Hexadecimal integer constant 0x00FF000000000000ULLULL is not valid.

ULLULL is not a valid ANSI C99 specifier.  GCC must let it thru, but other compilers do not.

Remove the extra constant specifiers from inside the bswap() macros and let UINT32/64_C add them naturally.

Note:
I'm doing testing of flatcc under AIX using the native IBM compiler, so I'll probably have some more suggestions/comments like this.

Thanks!

**Comment by mikkelfj** [comment]
Fixed, and thanks for reporting this - the portable library depends on such user feedback.
Please provide feedback on how flatcc works on AIX also if there are no further problems.
