### ISSUE TITLE
memory.h

### ISSUE THREAD

**Issue by thisboyiscrazy** [dvidelabs/flatcc#92]
builder.c includes memory.h this prevents building with esp-idf. I commented out the line and it built and run it with esp-idf. I also built it normally using ./scripts/build.sh and it built and ran.

is the include necessary?

**Comment by mikkelfj** [comment]
No it is an old misconception from ancient C. I thought it was already cleaned up. stdlib.h ought to do it.

**Comment by mikkelfj** [comment]
Fixed on master
