### ISSUE TITLE
flexbuffers (or how to have dynamic keys)

### ISSUE THREAD

**Issue by omidplus** [dvidelabs/flatcc#93]
Hi,
Is there any plan to support schema-less buffers as described [here](https://google.github.io/flatbuffers/flexbuffers.html)?

Thanks

**Comment by mikkelfj** [comment]
No, but I'd like to hear about your motivation if you have one that you can share.

FlexBuffers it is largely an independent format that shares some design philosofies with FlatBuffers such as 0-copy read access but it has not much else in common with the FlatBuffers format.

I have invested in high performance JSON parser and printers which can probably achieve a higher level of performance by receiving data as JSON and processing it as FlatBuffers or vice versa. The downside is that this still requires code generation for at least the sending or receiving part, but the other end can be flexible and can use generic JSON libraries if needed.

A FlatCC JSON parser handles about 500MB/s depending on circumstances. I'm not sure about the size differences between FlexBuffers and JSON, but I doubt the difference is significant, especially if compressed.

I might add support for other formats like CoAP or ProtoBuf similar to how JSON is handled, but it is a long term idea.

You could create a C++ flexbuffer to JSON converter which never has to change. Then import JSON to FlatBuffers via a FlatCC generated JSON parser.

**Comment by omidplus** [comment]
Thanks for your reply.

The main motivation is to be able to create some generic key-value structure with keys which cannot be known beforehand.

Using JSON is a good option for now.
This can also be done by creating a vector of some table which contains a key and value but it is not efficient as finding with key would be linear and also cannot guarantee unique keys.

I will be glad to implement this if I find time.

Thanks

**Comment by mikkelfj** [comment]
The above loops because that are many places where a vector should be sorted, but the actual sort operation is just two lines of code. The sort operation is done in-place without extra memory. The sort is unstable.

```
             mfields = (reflection_Field_mutable_vec_t)fields; 
             reflection_Field_vec_sort(mfields); 
```

You use the find method instead of scan to look up keys in sorted tables and it only works if there is key attribute on the key field.

**Comment by omidplus** [comment]
This is good for having dynamic keys and also is a good replacement for flexbuffers.
Thanks
