### ISSUE TITLE
flatcc build error

### ISSUE THREAD

**Issue by oathupdate** [dvidelabs/flatcc#95]
flatcc-master/include/flatcc/flatcc_types.h:48:33: error: ‘UINT32_MAX’ was not declared in this scope
 #define FLATBUFFERS_UOFFSET_MAX UINT32_MAX

**Comment by mikkelfj** [comment]
you are probably missing <stdint.h> could you try with -cstd=c11 or define -DFLATCC_PORTABLE?

```
cc -I include monster_example.c -o monster_example
cc -std=c11 -I include monster_example.c -o monster_example
cc -D FLATCC_PORTABLE -I include monster_example.c -o monster_example
```
https://github.com/dvidelabs/flatcc#compiling-for-read-only

Maybe some setting is missing for your environment, but it would help if you could tell some more.


Often <stdint.h> is not include if UINT8_MAX is defined such that you can include you own version, including pdstdint.h for backwards compat.

**Comment by mikkelfj** [comment]
https://github.com/dvidelabs/flatcc/blob/042d623a5848f42b59c45de8e5fa6531a4b5399e/include/flatcc/flatcc_types.h#L10-L12

**Comment by mikkelfj** [comment]
This one should go in with FLATCC_PORTABLE defined:
https://github.com/dvidelabs/flatcc/blob/master/include/flatcc/portable/pstdint.h

**Comment by mikkelfj** [comment]
I will not add these macros, as it is old non-std garbage, but if it is necessary for your environment, you can define them in your build.

https://sourceware.org/bugzilla/show_bug.cgi?id=15366
https://stackoverflow.com/questions/986426/what-do-stdc-limit-macros-and-stdc-constant-macros-mean

Please let me know if that works for you.
