### ISSUE TITLE
Possibly wrong return value in struct create functions?

### ISSUE THREAD

**Issue by vchrn** [dvidelabs/flatcc#98]
Good evening,

As far as I understand, all functions returning `int` values should return `0` on success and a non-zero value otherwise, however the following line:
https://github.com/dvidelabs/flatcc/blob/b85001117d22a6ac2ad5adcbdeec2898da7c1110/include/flatcc/reflection/flatbuffers_common_builder.h#L482

Generates functions which return 0 in all cases. I suspect it's a bug.

**Comment by mikkelfj** [comment]
Yes, that is wrong. I'm not sure if it should return a pointer or an integer in this case. Structs are a bit special because they are stored inline in a table.

**Comment by mikkelfj** [comment]
All other similar functions return integer, so return value remains int. The incorrect return code only happens in the very unlikely event that the builder runs out of memory just when the struct is being created. Normal operation has correct return value.

Please review fix
https://github.com/dvidelabs/flatcc/blob/eaa559d5b3f24dd89b7fead24709c786146ca3a1/include/flatcc/reflection/flatbuffers_common_builder.h#L482

Note: this is only generated code. Impact is all user generated code where common builder is generated, but as mentioned not likely of signficance except in very resource limited projects.
